export const LATEST_RELEASE = "2026-09-24-momentum-and-unit-pictures";
export const RELEASE_NOTES = [
  {date:"24 September 2026",title:"A picture on your unit",items:["Where a unit has a slide deck, its picture now sits at the top of that unit’s card in Lessons, so you can spot it at a glance.","Units without a deck look exactly as before."]},
  {date:"24 September 2026",title:"Your week at a glance",items:["The home screen now shows the last seven days and how many days in a row you have worked.","A day counts when you send homework, finish a spoken conversation, or send a recorded talk. Sending still counts if you are offline at the time.","Miss a day and nothing is taken away. Your best run is kept, and the counter simply starts again."]},
  {date:"24 September 2026",title:"Stay signed in, and your own dark mode",items:["You no longer have to sign in every time you open the app. Tick \u201cKeep me signed in on this device\u201d and it stays signed in for thirty days.","The app follows your phone\u2019s own light or dark setting from the moment it opens, including on the sign-in screen. Choose Light or Dark in Settings to override it.","The sign-in screen has been rebuilt to match the rest of the app, and shows the shape of your page while it opens.","One homework submission that cannot be sent no longer holds up the others, and a page that fails now shows a way back instead of a blank screen."]},
  {date:"23 September 2026",title:"Every sentence, not just the mistakes",items:["Writing reviews keep every original sentence in full, with its full correction and any optional improvement.","Sentences kept unchanged are marked Already correct. Transcription notes stay separate and are not assessed as student writing.","If a correction is missing, the sentence remains visible and is marked Needs review rather than being guessed correct."]},
  {date:"23 September 2026",title:"Voice, recordings and easier files",items:["Choose a conversation voice before starting. The speaking screen tries to keep an iPhone or iPad awake during a live chat.","Record, listen to and send Valentin’s individual homework talk inside the app.","Open saved documents in the page, and read Maya’s listening transcript directly under the audio.","Writing reviews show full sentences, including those kept as written; progress feedback opens below each entry instead of stretching sideways.","Add a profile picture on this device; the Home Screen icon now matches the r. logo.","On a private device, Rory can keep his teacher sign-in across app closes until the six-hour session expires."]},
  {date:"23 September 2026",title:"Find the right place faster",items:["Homework shows speaking, writing and assignments as distinct cards, with ready, upcoming and completed work separated.","Today puts current tasks first. Lessons, practice, resources, feedback and test prep have clearer names and paths.","Navigation is grouped by purpose on laptops and condensed into five clear destinations on phones."]},
  {date:"23 September 2026",title:"Clearer speaking homework",items:["Ferdi has one guided chat and one written answer each teaching week, with highlighted examples and sentence starters.","The app saves a voice conversation when it ends. There is no transcript to copy and paste.","Key words in Rory’s feedback are easier to spot."]},
  {date:"21 September 2026",title:"From paper to your learning file",items:["Scan handwritten pages or upload a PDF in My documents.","Keep your original, AI practice feedback and questions together, then add a revision.","Rory can upload to your profile too, and publish his own reviewed feedback."]},
  {date:"20 September 2026",title:"More room for your English",items:["A visual home screen connects lessons, speaking, practice and feedback.","The workspace now uses the available screen width on laptops and tablets, with simpler navigation on phones.","Choose Paper & blue, Quiet indigo or Warm clay, in light or dark mode.","Your existing homework, drafts, feedback and archived lesson links stay in place."]},
  {date:"19 September 2026",title:"Everything is easier to find",items:["A menu brings homework, lesson materials, progress and settings together.","Choose Light, Dark or System appearance, plus three text sizes.","Rory can preview a student’s pages without changing their work."]},
  {date:"18 September 2026",title:"A fresh start for the new term",items:["Sign in with your email and your own password, and stay signed in on your own device.","Current work and previous years have separate places.","Send your answers, check the receipt, then return for Rory’s feedback."]},
];
