"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {fetchCalendar,calendarAction} from "@/lib/calendar-client";
import {lessonDate,lessonTime,viennaDate,type CalendarData,type Lesson,type LessonRequest} from "@/lib/lesson-calendar";
import {isStudentPreview} from "@/lib/student-preview";
type Student={code:string;name:string};
type LessonDraft={id:string;code:string;date:string;time:string;duration:number;title:string;location:string;repeat:string;until:string;expectedSequence?:number};
const empty:CalendarData={ok:true,lessons:[],requests:[],breaks:[]};
function addDays(date:string,n:number){const d=new Date(date+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function initialDraft(code:string,date=viennaDate()):LessonDraft{return {id:crypto.randomUUID(),code,date,time:"",duration:90,title:"English lesson with Rory",location:"",repeat:"fortnightly",until:addDays(date,84)};}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="cal-field"><span>{label}</span>{children}</label>;}
export default function CalendarView({code,name,teacher=false,parent=false,students=[]}:{code:string;name:string;teacher?:boolean;parent?:boolean;students?:Student[]}){
  const [data,setData]=useState<CalendarData>(empty),[loaded,setLoaded]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [filter,setFilter]=useState(""),[month,setMonth]=useState(""),[day,setDay]=useState(""),[showPast,setShowPast]=useState(false);
  const [draft,setDraft]=useState<LessonDraft|null>(null),[requestLesson,setRequestLesson]=useState<Lesson|null>(null),[cancelLesson,setCancelLesson]=useState<Lesson|null>(null),[showBreak,setShowBreak]=useState(false);
  const [link,setLink]=useState(""),[linkScope,setLinkScope]=useState(""),[copyStatus,setCopyStatus]=useState("");
  const preview=isStudentPreview(code),alive=useRef(true);
  const refresh=useCallback(async()=>{try{const result=await fetchCalendar(code);if(!alive.current)return;if(result.ok){setData({ok:true,lessons:result.lessons||[],requests:result.requests||[],breaks:result.breaks||[]});setError("");}else setError(result.error||"Could not load the lesson calendar.");setLoaded(true);}catch{if(alive.current){setError("Could not load the lesson calendar. Reconnect and try again.");setLoaded(true);}}},[code]);
  useEffect(()=>{alive.current=true;setMonth(viennaDate().slice(0,7));void refresh();const focused=()=>void refresh();window.addEventListener("focus",focused);return()=>{alive.current=false;window.removeEventListener("focus",focused);};},[refresh]);
  // A link belongs to the exact selected scope; switching students must never
  // leave the previous student's link visible under the new student's name.
  useEffect(()=>{setLink("");setLinkScope("");setCopyStatus("");},[filter,code]);
  async function run(target:string,action:string,body:Record<string,unknown>,success:string){setBusy(true);setError("");setNotice("");try{const result=await calendarAction(target,action,body);if(result.ok){setNotice(success+(result.created?` ${result.created} lesson${result.created===1?"":"s"} saved.`:"")+(result.skipped?` ${result.skipped} date${result.skipped===1?"":"s"} skipped during breaks.`:"")+(result.cancelled?` ${result.cancelled} existing lesson${result.cancelled===1?"":"s"} cancelled.`:""));await refresh();}else setError(result.error||"Could not confirm the change. Keep this form open and check the calendar before retrying.");return result.ok;}catch{setError("Could not confirm the change. Keep this form open and check the calendar before retrying.");return false;}finally{setBusy(false);}}
  const selected=teacher?filter||students[0]?.code||"":code;
  const visible=data.lessons.filter(l=>!filter||l.studentCode===filter);
  const sorted=visible.filter(l=>showPast||new Date(l.end).getTime()>Date.now()).filter(l=>!day||l.date===day).sort((a,b)=>a.start.localeCompare(b.start));
  const requests=data.requests.filter(r=>!filter||r.studentCode===filter),breaks=data.breaks.filter(b=>!filter||b.studentCode===filter);
  const days=useMemo(()=>{if(!month)return [];const first=new Date(month+"-01T12:00:00Z"),count=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7;return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>`${month}-${String(i+1).padStart(2,"0")}`)];},[month]);
  const monthTitle=month?new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(month+"-01T12:00:00Z")):"Lesson calendar";
  function changeMonth(amount:number){const d=new Date(month+"-01T12:00:00Z");d.setUTCMonth(d.getUTCMonth()+amount);setMonth(d.toISOString().slice(0,7));setDay("");}
  async function createLink(){setBusy(true);setError("");try{const target=teacher?filter||"__teacher__":code;const r=await calendarAction(target,"calendarLink");if(r.ok&&r.calendarToken){const u=new URL("/api/calendar/",window.location.origin);u.searchParams.set("code",r.scope||target);u.searchParams.set("token",r.calendarToken);setLink(u.toString());setLinkScope(target);setCopyStatus("");setNotice("Private calendar link created. Any older link for this calendar has stopped working.");}else setError(r.error||"Could not create a calendar link.");}catch{setError("Could not create a calendar link. Reconnect and try again.");}finally{setBusy(false);}}
  async function revokeLink(){const target=teacher?filter||"__teacher__":code;if(await run(target,"calendarRevoke",{},"Calendar link disabled. Previously downloaded lesson details may remain in your calendar.")){setLink("");setLinkScope("");}}
  async function copyLink(){try{await navigator.clipboard.writeText(link);setCopyStatus("Link copied");}catch{setCopyStatus("Select the link below and copy it.");}}
  function edit(l:Lesson){setDraft({id:l.id,code:l.studentCode,date:l.date,time:l.time,duration:l.duration,title:l.title,location:l.location,repeat:"once",until:l.date,expectedSequence:l.sequence});setError("");setNotice("");}
  return <main className="cal-page">
    <header className="re-page-heading"><p className="re-eyebrow">{teacher?"PLAN YOUR TEACHING":"YOUR LESSON TIMES"}</p><h1>Lesson calendar</h1><p>{teacher?"Plan the term, check requests and keep everyone’s calendar up to date.":`${name}’s lessons with Rory, all in one place.`}</p></header>
    <div className="cal-toolbar"><p className="cal-zone">All times are in <strong>Vienna time</strong>.</p>{teacher&&<div className="cal-tools"><label className="sr-only" htmlFor="cal-filter">Choose a student</label><select id="cal-filter" value={filter} onChange={e=>{setFilter(e.target.value);setDay("");}}><option value="">All students</option>{students.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select><button className="cal-primary" disabled={busy||!students.length} onClick={()=>{setDraft(initialDraft(selected,day||viennaDate()));setError("");setNotice("");}}>+ Schedule lessons</button><button className="cal-button" disabled={busy||!students.length} onClick={()=>setShowBreak(true)}>Add school break</button></div>}</div>
    {preview&&<p className="cal-info">Teacher preview is read-only. Return to your teacher workspace to change times or connect a calendar.</p>}
    {!loaded&&<p role="status" className="cal-info">Loading lesson times…</p>}
    {error&&<div role="alert" className="cal-alert">{error}<button className="cal-button" disabled={busy} onClick={()=>void refresh()}>Refresh calendar</button></div>}
    {notice&&<p role="status" className="cal-success">{notice}</p>}
    <div className="cal-layout"><section className="cal-month" aria-label="Monthly lesson calendar"><div className="cal-month-heading"><button className="cal-icon-button" aria-label="Previous month" onClick={()=>changeMonth(-1)}>‹</button><h2>{monthTitle}</h2><button className="cal-icon-button" aria-label="Next month" onClick={()=>changeMonth(1)}>›</button></div><div className="cal-grid">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(w=><span className="cal-weekday" key={w}>{w}</span>)}{days.map((date,i)=>{if(!date)return <span key={`empty-${i}`}/>;const lessons=visible.filter(l=>l.date===date&&l.status==="scheduled"),blocked=breaks.some(b=>date>=b.from&&date<=b.to);return <button key={date} type="button" aria-pressed={day===date} aria-label={`${lessonDate(date)}, ${lessons.length} lesson${lessons.length===1?"":"s"}${blocked?", school break":""}`} className={`cal-day ${day===date?"is-selected":""} ${date===viennaDate()?"is-today":""} ${blocked?"is-break":""}`} onClick={()=>setDay(day===date?"":date)}><span>{Number(date.slice(-2))}</span>{lessons.slice(0,2).map(l=><small key={l.id}>{l.time}{teacher?` ${l.studentName.split(" ")[0]}`:""}</small>)}{lessons.length>2&&<small>+{lessons.length-2} more</small>}{blocked&&!lessons.length&&<small className="cal-break-mark">Break</small>}</button>;})}</div><div className="cal-month-foot"><button className="cal-text-button" onClick={()=>{setMonth(viennaDate().slice(0,7));setDay("");}}>This month</button><span>Shaded dates are lesson breaks.</span></div></section>
    <section className="cal-agenda"><div className="cal-section-heading"><h2>{day?lessonDate(day):"Upcoming lessons"}</h2>{day&&<button className="cal-text-button" onClick={()=>setDay("")}>Show all</button>}</div><label className="cal-check"><input type="checkbox" checked={showPast} onChange={e=>setShowPast(e.target.checked)}/>Include past lessons</label>
      {loaded&&!sorted.length&&<div className="cal-empty"><span aria-hidden>◷</span><h3>{day?"No lessons on this date":"Lesson dates to be confirmed"}</h3><p>{teacher?"Schedule the first confirmed lesson, then repeat it every two weeks through the term.":"Rory will add your confirmed dates here. You can connect your calendar once they’re ready."}</p></div>}
      <div className="cal-lesson-list">{sorted.map(l=><article key={l.id} className={`cal-lesson ${l.status==="cancelled"?"is-cancelled":""}`}><div className="cal-lesson-top"><p>{lessonDate(l.date)}</p><span className={`cal-badge ${l.status}`}>{l.status==="cancelled"?"Cancelled":"Scheduled"}</span></div><h3>{l.time}–{lessonTime(l.end)} <small>{l.duration} min</small></h3><p className="cal-lesson-title">{teacher?`${l.studentName} · `:""}{l.title}</p>{l.location&&<p className="cal-location">{l.location}</p>}<div className="cal-lesson-actions">{teacher?<><button className="cal-button" disabled={busy} onClick={()=>edit(l)}>{l.status==="cancelled"?"Rebook":"Change time"}</button>{l.status!=="cancelled"&&<button className="cal-text-button" disabled={busy} onClick={()=>setCancelLesson(l)}>Cancel lesson</button>}</>:!preview&&l.status==="scheduled"&&new Date(l.end).getTime()>Date.now()&&(requests.some(r=>r.lessonId===l.id&&r.status==="pending")?<span className="cal-pending">Time change requested · awaiting Rory</span>:<button className="cal-button" disabled={busy} onClick={()=>setRequestLesson(l)}>Request a different time</button>)}</div></article>)}</div>
    </section></div>
    {!!requests.length&&<section className="cal-panel"><div className="cal-section-heading"><h2>Time-change requests</h2><span>{requests.filter(r=>r.status==="pending").length} awaiting reply</span></div>{requests.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=><RequestCard key={r.id} request={r} lesson={data.lessons.find(l=>l.id===r.lessonId&&l.studentCode===r.studentCode)} teacher={teacher} busy={busy} onRespond={status=>void run(r.studentCode,"teacherCalendarRespond",{id:r.id,status},status==="accepted"?"New lesson time confirmed.":"Request declined. The original lesson time stays in place.")}/>)}</section>}
    <section className="cal-panel"><div className="cal-section-heading"><h2>School breaks</h2><span>Fortnightly lessons pause during breaks</span></div>{!breaks.length?<p className="cal-muted">No break dates entered yet.{teacher?" Add confirmed holiday dates before scheduling the term.":" Rory will confirm which dates are excluded."}</p>:breaks.map(b=><div className="cal-break-row" key={`${b.studentCode}-${b.id}`}><div><strong>{teacher?`${b.studentName} · `:""}{b.label}</strong><p>{lessonDate(b.from)} – {lessonDate(b.to)}</p></div>{teacher&&<button disabled={busy} className="cal-text-button" onClick={()=>void run(b.studentCode,"teacherCalendarRemoveBreak",{id:b.id},"Break removed. Cancelled lessons stay cancelled; use Rebook to restore a lesson.")}>Remove break</button>}</div>)}</section>
    {!preview&&<section className="cal-panel cal-connect"><div><p className="re-eyebrow">TAKE YOUR LESSONS WITH YOU</p><h2>Connect your calendar</h2><p>Subscribe in Google Calendar, Apple Calendar or Outlook. {teacher?(filter?`${students.find(s=>s.code===filter)?.name||"This student"}’s lessons only.`:"Your link includes all students’ lessons."):"Your link includes only these lessons."} Changes made here will appear when your calendar refreshes.</p><p className="cal-muted">Calendar updates can be delayed, sometimes by more than a day. Check the app for the latest time. This is a subscription: changes in your personal calendar won’t change the booking here.</p></div><div className="cal-link-controls"><button className="cal-primary" disabled={busy} onClick={()=>void createLink()}>Create or replace private link</button><button className="cal-text-button" disabled={busy} onClick={()=>void revokeLink()}>Disable calendar link</button></div><p className="cal-muted">Replacing a link stops the previous one from updating. Anyone with the link can see lesson times and locations; share it only with the people who need it.</p>{link&&linkScope===(teacher?filter||"__teacher__":code)&&<div className="cal-link-result"><label className="cal-field"><span>Private subscription link</span><input readOnly value={link} onFocus={e=>e.target.select()}/></label><div className="cal-link-controls"><button className="cal-button" onClick={()=>void copyLink()}>Copy link</button><a className="cal-button" href={link.replace(/^https?:/,"webcal:")} referrerPolicy="no-referrer">Subscribe in Apple Calendar</a><span role="status">{copyStatus}</span></div><details><summary>How to add it to Google Calendar or Outlook</summary><p><strong>Google:</strong> open Google Calendar in a desktop browser. Next to Other calendars, choose + → From URL, paste this link and add the calendar.</p><p><strong>Outlook:</strong> open Calendar → Add calendar → Subscribe from web, paste the link, name the calendar and save.</p><p><strong>Apple:</strong> use the Subscribe button above, or add a subscription calendar and paste the link.</p></details></div>}</section>}
    {parent&&<a className="cal-text-button" href={`/p/${code}/`}>← Feedback & progress</a>}
    {draft&&<LessonEditor draft={draft} setDraft={setDraft} students={students} busy={busy} error={error} onClose={()=>setDraft(null)} onSave={async()=>{const {code:target,...body}=draft;if(await run(target,"teacherCalendarSave",body,"Lesson calendar updated."))setDraft(null);}}/>}
    {requestLesson&&<RequestEditor lesson={requestLesson} busy={busy} error={error} onClose={()=>setRequestLesson(null)} onSave={async body=>{if(await run(code,"calendarRequest",body,"Request sent to Rory. Your current lesson time stays in place until approved."))setRequestLesson(null);}}/>}
    {showBreak&&<BreakEditor students={students} selected={selected} busy={busy} error={error} onClose={()=>setShowBreak(false)} onSave={async(target,body)=>{if(await run(target,"teacherCalendarBreak",body,"School break added."))setShowBreak(false);}}/>}
    {cancelLesson&&<CalendarDialog title="Cancel this lesson?" onClose={()=>setCancelLesson(null)} busy={busy}><p>{teacher?cancelLesson.studentName+" · ":""}{lessonDate(cancelLesson.date)} at {cancelLesson.time}. This cancellation will appear in subscribed calendars when they refresh.</p>{error&&<p className="cal-alert" role="alert">{error}</p>}<div className="cal-dialog-actions"><button className="cal-button" disabled={busy} onClick={()=>setCancelLesson(null)}>Keep lesson</button><button className="cal-primary" disabled={busy} onClick={async()=>{if(await run(cancelLesson.studentCode,"teacherCalendarCancel",{id:cancelLesson.id,expectedSequence:cancelLesson.sequence},"Lesson cancelled."))setCancelLesson(null);}}>{busy?"Saving…":"Cancel lesson"}</button></div></CalendarDialog>}
  </main>;
}
function CalendarDialog({title,children,onClose,busy}:{title:string;children:React.ReactNode;onClose:()=>void;busy:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="cal-dialog" aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="cal-dialog-heading"><h2>{title}</h2><button type="button" aria-label="Close" className="cal-icon-button" disabled={busy} onClick={onClose}>×</button></div>{children}</dialog>;}
function LessonEditor({draft,setDraft,students,busy,error,onClose,onSave}:{draft:LessonDraft;setDraft:(d:LessonDraft)=>void;students:Student[];busy:boolean;error:string;onClose:()=>void;onSave:()=>Promise<void>}){const edit=draft.expectedSequence!==undefined;const patch=(d:Partial<LessonDraft>)=>setDraft({...draft,...d});return <CalendarDialog title={edit?"Change lesson":"Schedule lessons"} onClose={onClose} busy={busy}><form onSubmit={e=>{e.preventDefault();void onSave();}}><div className="cal-form-grid"><Field label="Student"><select required disabled={edit||busy} value={draft.code} onChange={e=>patch({code:e.target.value})}>{students.map(s=><option value={s.code} key={s.code}>{s.name}</option>)}</select></Field><Field label="Lesson title"><input maxLength={120} required value={draft.title} onChange={e=>patch({title:e.target.value})}/></Field><Field label={edit?"Lesson date":"First confirmed date"}><input type="date" required value={draft.date} onChange={e=>patch({date:e.target.value,...(!edit&&draft.until<e.target.value?{until:addDays(e.target.value,84)}:{})})}/></Field><Field label="Start time · Vienna"><input type="time" required value={draft.time} onChange={e=>patch({time:e.target.value})}/></Field><Field label="Length in minutes"><input type="number" min={15} max={240} required value={draft.duration} onChange={e=>patch({duration:Number(e.target.value)})}/></Field><Field label="Location or meeting link"><input maxLength={200} value={draft.location} onChange={e=>patch({location:e.target.value})}/></Field>{!edit&&<><Field label="Repeat"><select value={draft.repeat} onChange={e=>patch({repeat:e.target.value})}><option value="once">One lesson</option><option value="fortnightly">Every two weeks</option></select></Field>{draft.repeat==="fortnightly"&&<Field label="Through this date"><input type="date" min={draft.date} max={addDays(draft.date||viennaDate(),366)} required value={draft.until} onChange={e=>patch({until:e.target.value})}/></Field>}</>}</div><p className="cal-info">{edit?"This changes only the selected lesson.":"Entered school breaks are skipped. The every-two-week pattern stays anchored to the first date. Add holiday ranges before scheduling the term."}</p>{error&&<p className="cal-alert" role="alert">{error}</p>}<div className="cal-dialog-actions"><button type="button" className="cal-button" disabled={busy} onClick={onClose}>Back</button><button className="cal-primary" disabled={busy}>{busy?"Saving…":edit?"Save lesson":"Schedule lessons"}</button></div></form></CalendarDialog>;}
function RequestEditor({lesson,busy,error,onClose,onSave}:{lesson:Lesson;busy:boolean;error:string;onClose:()=>void;onSave:(b:Record<string,unknown>)=>Promise<void>}){const [id]=useState(()=>crypto.randomUUID()),[date,setDate]=useState(lesson.date),[time,setTime]=useState(lesson.time),[message,setMessage]=useState("");return <CalendarDialog title="Request a different time" onClose={onClose} busy={busy}><p>Your current lesson is {lessonDate(lesson.date)} at {lesson.time}. It stays booked until Rory accepts your request.</p><form onSubmit={e=>{e.preventDefault();void onSave({id,lessonId:lesson.id,date,time,message});}}><div className="cal-form-grid"><Field label="Preferred date"><input type="date" required min={viennaDate()} value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Preferred time · Vienna"><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field></div><Field label="Message to Rory (optional)"><textarea maxLength={500} rows={3} value={message} onChange={e=>setMessage(e.target.value)}/></Field>{error&&<p role="alert" className="cal-alert">{error}</p>}<div className="cal-dialog-actions"><button type="button" className="cal-button" disabled={busy} onClick={onClose}>Back</button><button className="cal-primary" disabled={busy}>{busy?"Sending…":"Send request"}</button></div></form></CalendarDialog>;}
function BreakEditor({students,selected,busy,error,onClose,onSave}:{students:Student[];selected:string;busy:boolean;error:string;onClose:()=>void;onSave:(code:string,b:Record<string,unknown>)=>Promise<void>}){const [id]=useState(()=>crypto.randomUUID()),[code,setCode]=useState(selected),[from,setFrom]=useState(""),[to,setTo]=useState(""),[label,setLabel]=useState("School break");return <CalendarDialog title="Add a school break" onClose={onClose} busy={busy}><form onSubmit={e=>{e.preventDefault();void onSave(code,{id,from,to,label});}}><div className="cal-form-grid"><Field label="Student"><select value={code} onChange={e=>setCode(e.target.value)}>{students.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></Field><Field label="Break name"><input required maxLength={120} value={label} onChange={e=>setLabel(e.target.value)}/></Field><Field label="First day (included)"><input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Last day (included)"><input type="date" min={from} required value={to} onChange={e=>setTo(e.target.value)}/></Field></div><p className="cal-info">Existing lessons in this range will be cancelled. Future repeating lessons will skip these dates. Removing a break later does not automatically rebook cancelled lessons.</p>{error&&<p className="cal-alert" role="alert">{error}</p>}<div className="cal-dialog-actions"><button type="button" className="cal-button" disabled={busy} onClick={onClose}>Back</button><button className="cal-primary" disabled={busy}>{busy?"Saving…":"Add break and skip lessons"}</button></div></form></CalendarDialog>;}
function RequestCard({request:r,lesson,teacher,busy,onRespond}:{request:LessonRequest;lesson?:Lesson;teacher:boolean;busy:boolean;onRespond:(s:string)=>void}){const stale=lesson?.status!=="scheduled";return <article className="cal-request"><div><strong>{teacher?`${r.studentName} · `:""}{lessonDate(r.date)} at {r.time}</strong><p>{lesson?`Current booking: ${lessonDate(lesson.date)} at ${lesson.time}`:"Original lesson unavailable"}</p>{r.message&&<p className="cal-request-message">{r.message}</p>}<span className={`cal-badge ${r.status}`}>{r.status==="pending"?"Awaiting Rory":r.status==="accepted"?"Accepted":"Declined"}</span></div>{teacher&&r.status==="pending"&&<div className="cal-request-actions"><button className="cal-primary" disabled={busy||stale} onClick={()=>onRespond("accepted")}>Accept new time</button><button className="cal-button" disabled={busy} onClick={()=>onRespond("declined")}>Decline</button></div>}</article>;}
