"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {documentRequest,fileBase64,validateDocumentFiles,type LearnerDocument,type DocumentMessage} from '@/lib/documents';
import {isStudentPreview} from '@/lib/student-preview';
import FeedbackText from '@/components/FeedbackText';
const Scanner=dynamic(()=>import('@/components/DocumentScanner'),{ssr:false});
function DocIcon({camera=false}:{camera?:boolean}){return <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{camera?<><path d="M8 5l1-2h6l1 2h4a1 1 0 0 1 1 1v13H3V6a1 1 0 0 1 1-1z"/><circle cx="12" cy="12" r="4"/></>:<><path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/></>}</svg>}
const statusLabel=(d:LearnerDocument)=>d.feedback?'Rory’s feedback ready':d.processing?'Reading your work':d.status==='ready'?'AI practice feedback':d.status==='error'?'Saved · reading needs a retry':'Saved · ready to read';
const dateLabel=(s:string)=>new Date(s).toLocaleDateString(undefined,{day:'numeric',month:'short'});
export default function DocumentsView({code,name,teacher=false}:{code:string;name:string;teacher?:boolean}){
  const preview=isStudentPreview(code),disabled=preview;
  const [documents,setDocuments]=useState<LearnerDocument[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [files,setFiles]=useState<File[]>([]),[title,setTitle]=useState(''),[context,setContext]=useState(''),[parentId,setParentId]=useState(''),[scanner,setScanner]=useState(false),[busy,setBusy]=useState('');
  const [selected,setSelected]=useState<LearnerDocument|null>(null),[messages,setMessages]=useState<DocumentMessage[]>([]),[question,setQuestion]=useState(''),[feedback,setFeedback]=useState('');
  const [fileView,setFileView]=useState<{url:string;name:string;type:string}|null>(null),[selectedLoading,setSelectedLoading]=useState(false);
  const input=useRef<HTMLInputElement>(null),uploadForm=useRef<HTMLFormElement>(null),uploadId=useRef(crypto.randomUUID()),messageId=useRef(crypto.randomUUID()),selectedId=useRef<string|null>(null),lastReviewed=useRef(''),fileUrl=useRef('');
  useEffect(()=>{if(!files.length)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[files.length]);
  const rpc=useCallback((body:Record<string,unknown>)=>documentRequest(code,teacher,body),[code,teacher]);
  const refresh=useCallback(async()=>{const r=await rpc({action:'documents'});setLoaded(true);if(r.ok){setDocuments(r.documents||[]);}else setError(r.error||'Could not load saved documents.');},[rpc]);
  useEffect(()=>{void refresh();return()=>{if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);};},[refresh]);
  const loadDocument=useCallback(async(id:string,initial=false)=>{
    if(initial){selectedId.current=id;setSelectedLoading(true);setSelected(null);setMessages([]);setError('');setQuestion('');messageId.current=crypto.randomUUID();lastReviewed.current='';if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);fileUrl.current='';setFileView(null);}
    const r=await rpc({action:'document',id});if(selectedId.current!==id)return;
    setSelectedLoading(false);if(r.ok&&r.document){setSelected(r.document);setMessages(r.messages||[]);if(initial||lastReviewed.current!==r.document.reviewed){setFeedback(r.document.feedback);lastReviewed.current=r.document.reviewed;}setDocuments(ds=>ds.map(d=>d.id===id?{...d,...r.document}:d));}else setError(r.error||'Could not open that document.');
  },[rpc]);
  useEffect(()=>{if(!selected||(!selected.processing&&busy!=='analyse'&&busy!=='chat'))return;const id=selected.id,t=setInterval(()=>void loadDocument(id),6000);return()=>clearInterval(t);},[selected?.id,selected?.processing,busy,loadDocument]);
  function chooseFiles(next:File[]){const problem=validateDocumentFiles(next);setError(problem);if(problem)return;setFiles(next);uploadId.current=crypto.randomUUID();if(!title)setTitle(next.length===1?next[0].name.replace(/\.[^.]+$/,''):'Scanned work');setNotice('');}
  async function analyse(id:string){setBusy('analyse');setError('');setNotice('Reading the saved document. You can leave this page and come back to check it.');setSelected(d=>d?.id===id?{...d,processing:true,status:'analysing'}:d);const r=await rpc({action:'documentAnalyse',id});setBusy('');if(!r.ok)setError(r.error||'Your document is saved. The reading could not be confirmed; check it again before retrying.');setNotice(r.pending?'Still reading. The result will appear here when ready.':'');await loadDocument(id);await refresh();}
  async function upload(e:React.FormEvent){e.preventDefault();if(disabled||busy)return;const problem=validateDocumentFiles(files);if(problem){setError(problem);return;}setBusy('upload');setError('');setNotice('Saving the original to this student’s profile…');try{const encoded=await Promise.all(files.map(async f=>({name:f.name,type:f.type,data:await fileBase64(f)})));const r=await rpc({action:'documentUpload',id:uploadId.current,title:title.trim(),context,parentId,files:encoded});if(!r.ok||!r.received||!r.document)throw new Error(r.error||'The upload has not been confirmed. Keep this page open and retry to check the same upload.');const id=r.document.id;setFiles([]);setTitle('');setContext('');setParentId('');uploadId.current=crypto.randomUUID();setBusy('');setNotice('Original saved. Preparing practice feedback…');await refresh();await loadDocument(id,true);await analyse(id);}catch(e){setError((e as Error).message);setNotice('');setBusy('');}}
  async function chat(e:React.FormEvent){e.preventDefault();if(!selected||!question.trim()||busy||disabled)return;const id=selected.id;setBusy('chat');setError('');const r=await rpc({action:'documentChat',id,messageId:messageId.current,question:question.trim()});setBusy('');if(r.ok&&!r.pending){setQuestion('');messageId.current=crypto.randomUUID();}else setError(r.pending?'The helper is still working. Your question is kept here; check again in a moment.':r.error||'Could not confirm the reply. Your question is kept here.');await loadDocument(id);}
  async function publish(){if(!selected||!teacher||disabled)return;setBusy('review');setError('');const r=await rpc({action:'teacherDocumentReview',id:selected.id,feedback});setBusy('');if(r.ok){setNotice(`Your feedback is now visible to ${name}.`);await loadDocument(selected.id);await refresh();}else setError(r.error||'Could not save your feedback.');}
  async function openFile(index:number){if(!selected)return;const id=selected.id;setBusy('file');setError('');const r=await rpc({action:'documentFile',id,index});setBusy('');if(selectedId.current!==id)return;if(!r.ok||!r.file){setError(r.error||'Could not open the original.');return;}const bytes=Uint8Array.from(atob(r.file.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:r.file.type}));if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);fileUrl.current=url;setFileView({url,name:r.file.name,type:r.file.type});}
  function revision(){if(!selected)return;setParentId(selected.id);setTitle(`Revision: ${selected.title}`.slice(0,150));setContext(selected.context);setFiles([]);uploadId.current=crypto.randomUUID();uploadForm.current?.scrollIntoView({behavior:'smooth',block:'start'});setNotice('Add the revised work above. The earlier version will stay saved.');}
  return <div className="documents-space">
    <section className="doc-hero"><div><p className="doc-eyebrow">{teacher?`${name.toUpperCase()}’S LEARNING FILE`:'FROM PAGE TO PROGRESS'}</p><h1>{teacher?'Documents & feedback':'My documents'}</h1><p>{teacher?`Scan or upload work for ${name}. Originals, practice feedback and follow-up questions stay together here.`:'A photo of your page. A little help with the tricky parts. A chance to try again.'}</p></div><div className="doc-paper-art" aria-hidden="true"><span className="doc-art-spark">✦</span><div><i/><i/><i/><b>one small<br/>step forward.</b><i/></div><span className="doc-art-badge">✓</span></div></section>
    <ol className="doc-steps" aria-label="How it works"><li><span>1</span><div>Save your work<small>Scan pages or upload a file</small></div></li><li><span>2</span><div>Read & explore<small>AI suggestions and questions</small></div></li><li><span>3</span><div>Feedback & retry<small>Rory’s review, then your next draft</small></div></li></ol>
    {preview&&<p className="doc-notice">Student preview is read-only. Add documents from the teacher workspace.</p>}
    <form ref={uploadForm} className="doc-upload-card" onSubmit={e=>void upload(e)}>
      <div className="doc-upload-actions"><button type="button" className="doc-upload-option" disabled={disabled||!!busy} onClick={()=>setScanner(true)}><span><DocIcon camera/></span><strong>Scan pages</strong><small>Use your phone, iPad or laptop camera</small></button><button type="button" className="doc-upload-option" disabled={disabled||!!busy} onClick={()=>input.current?.click()}><span><DocIcon/></span><strong>Upload a document</strong><small>PDF or photos · up to 2.5 MB total</small></button><input ref={input} type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" hidden onChange={e=>{chooseFiles(Array.from(e.target.files||[]));e.target.value='';}}/></div>
      <p className="doc-privacy">Saved privately to {teacher?`${name}’s`:'your'} profile, visible to {teacher?`${name} and you`:'you and Rory'}. AI reads the file to offer practice suggestions; it does not assign a grade.</p>
      {(files.length>0||parentId)&&<div className="doc-upload-details">{parentId&&<p className="doc-notice">New revision · earlier work stays saved <button type="button" className="doc-link" onClick={()=>setParentId('')}>Make this separate work</button></p>}<div className="doc-selected-files">{files.map((f,i)=><span key={`${i}-${f.name}`}><DocIcon/>{f.name} <small>{Math.ceil(f.size/1000)} KB</small></span>)}</div><label>Title<input required maxLength={150} value={title} disabled={!!busy} onChange={e=>setTitle(e.target.value)} placeholder="e.g. My school blog — first draft"/></label><label>Task or question <span className="doc-muted">(optional)</span><textarea value={context} maxLength={2000} rows={2} disabled={!!busy} onChange={e=>setContext(e.target.value)} placeholder="What were you asked to do? Add the task instructions or what you’d like help with."/></label><div className="doc-button-row"><button className="doc-primary" disabled={disabled||!!busy||!files.length||!title.trim()}>{busy==='upload'?'Saving original…':`Save ${teacher?`to ${name}’s profile`:'& read my work'}`}</button><button type="button" className="doc-secondary" disabled={!!busy} onClick={()=>{setFiles([]);setParentId('');setTitle('');setContext('');}}>Cancel</button></div></div>}
    </form>
    {error&&<div className="doc-error" role="alert">{error}</div>}{notice&&<p className="doc-notice" role="status">{notice}</p>}
    <div className="doc-workspace"><section className="doc-library"><header><h2>Saved work <span>{documents.length}</span></h2><button className="doc-link" onClick={()=>{setError('');void refresh();}}>Refresh</button></header>{!loaded?<p role="status" className="doc-muted">Opening your learning file…</p>:!documents.length?<div className="doc-empty"><DocIcon/><h3>Every draft starts somewhere.</h3><p>Scan a handwritten page or add a PDF. You’ll find it here whenever you need it.</p></div>:<div className="doc-list">{documents.map(d=><button key={d.id} className={`doc-list-item ${selectedId.current===d.id?'is-selected':''}`} aria-pressed={selectedId.current===d.id} disabled={!!busy} onClick={()=>void loadDocument(d.id,true)}><span className="doc-list-icon"><DocIcon/></span><div><strong>{d.title}</strong><small>{dateLabel(d.created)} · added by {d.uploadedBy}{d.parentId?' · revision':''}</small><span className={`doc-status ${d.feedback?'reviewed':''}`}>{statusLabel(d)}</span></div><span aria-hidden="true">↗</span></button>)}</div>}</section>
      <section className="doc-detail" aria-label="Selected document">{selectedLoading?<p role="status">Opening document…</p>:!selected?<div className="doc-detail-empty"><span aria-hidden="true">✧</span><h2>A place to work things out.</h2><p>Choose a saved document to see the original, explore the feedback and ask a question.</p></div>:<>
        <header className="doc-detail-heading"><div><p className="doc-eyebrow">{selected.parentId?'REVISED WORK':'SAVED ORIGINAL'}</p><h2>{selected.title}</h2><p className="doc-muted">Added by {selected.uploadedBy} · {dateLabel(selected.created)}</p></div><button className="doc-link" disabled={!!busy} onClick={()=>void loadDocument(selected.id)}>Check for updates</button></header>
        {selected.context&&<p className="doc-task-context">{selected.context}</p>}{selected.parentId&&<button className="doc-link" onClick={()=>void loadDocument(selected.parentId,true)}>← Open earlier version</button>}
        <div className="doc-originals">{selected.files.map(f=><button key={f.index} className="doc-secondary" disabled={!!busy} onClick={()=>void openFile(f.index)}><DocIcon/>Open {selected.files.length>1?`page ${f.index+1}`:'original'}</button>)}</div>
        {fileView&&<div className="doc-file-preview"><div><strong>{fileView.name}</strong><a className="doc-link" href={fileView.url} download={fileView.name}>Download original</a></div>{fileView.type==='application/pdf'?<iframe src={fileView.url} title="Original PDF" sandbox=""/>:<img src={fileView.url} alt="Original uploaded work"/>}</div>}
        {selected.analysis?<>
          <div className="doc-analysis-heading"><span aria-hidden="true">✦</span><div><h3>Let’s look at your work</h3><p>AI practice feedback · check suggestions against the original</p></div></div><p className="doc-summary">{selected.analysis.summary}</p>
          {(selected.analysis.coverage!=='complete'||selected.analysis.uncertainties.length>0)&&<div className="doc-reading-note"><strong>{selected.analysis.coverage==='unreadable'?'A clearer scan is needed':selected.analysis.coverage==='partial'?'Some parts could not be read':'Check these readings'}</strong>{selected.analysis.uncertainties.map((s,i)=><p key={i}>{s}</p>)}<p>Unclear handwriting is not treated as a language mistake.</p></div>}
          <details className="doc-transcript"><summary>Read the transcription <span>Original wording · possible reading errors</span></summary><p>{selected.analysis.transcription||'No readable text was found.'}</p></details>
          {selected.analysis.strengths.length>0&&<div className="doc-strengths"><h3>What’s working</h3><ul>{selected.analysis.strengths.map((s,i)=><li key={i}>{s}</li>)}</ul></div>}
          {selected.analysis.corrections.length>0&&<div className="doc-corrections"><h3>A few useful changes</h3>{selected.analysis.corrections.map((c,i)=><article key={i}><div><small>YOUR WORDS</small><p>{c.original}</p></div><span aria-hidden="true">→</span><div><small>TRY THIS</small><p>{c.suggestion}</p></div><p>{c.explanation}</p></article>)}</div>}
          {selected.analysis.retry&&<div className="doc-retry"><span aria-hidden="true">↺</span><div><h3>Your next small step</h3><p>{selected.analysis.retry}</p></div></div>}
        </>:<div className="doc-reading-note"><h3>{selected.processing?'Reading the saved pages…':'Your original is saved.'}</h3><p>{selected.processing?'The reading may take a minute or two. You can return later to see the result.':selected.error||'Read the document to get practice feedback and ask questions about it.'}</p><button className="doc-primary" disabled={disabled||!!busy||selected.processing} onClick={()=>void analyse(selected.id)}>{selected.status==='error'?'Retry reading':'Read & analyse'}</button></div>}
        <div className="doc-teacher-feedback"><p className="doc-eyebrow">RORY’S REVIEW</p>{teacher?<><h3>Your feedback for {name}</h3><label className="sr-only" htmlFor="document-feedback">Teacher feedback</label><textarea id="document-feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} maxLength={6000} rows={5} placeholder="Add your reviewed feedback and the next step…"/><p className="doc-muted">Key instruction words are highlighted for the student. Add **double stars** around another short phrase to highlight it.</p><button className="doc-primary" disabled={disabled||!!busy||!feedback.trim()||feedback===selected.feedback} onClick={()=>void publish()}>Publish feedback to {name}</button><p className="doc-muted">Published feedback is visible in this student’s learning file. AI suggestions stay separately labelled.</p></>:selected.feedback?<><h3>Feedback from Rory</h3><p className="doc-preserve"><FeedbackText text={selected.feedback}/></p><small>Reviewed {dateLabel(selected.reviewed)}</small></>:<><h3>Waiting for Rory’s review</h3><p>The suggestions above are AI practice advice. Rory’s own feedback will appear here after he reviews your work.</p></>}</div>
        {selected.analysis&&<section className="doc-chat"><h3>Ask about this document <span>AI helper</span></h3><p className="doc-muted">Ask for an explanation, a hint or a practice example. This conversation is saved with the work and visible to Rory and {teacher?name:'you'}.</p>{!messages.length&&<div className="doc-question-chips">{['Explain one change','Give me a hint for my retry','What should I practise next?'].map(q=><button key={q} className="doc-secondary" disabled={disabled||!!busy} onClick={()=>{setQuestion(q);messageId.current=crypto.randomUUID();}}>{q}</button>)}</div>}<div className="doc-conversation" aria-live="polite">{messages.map(m=><div key={m.id}><div className="doc-chat-question"><small>{m.askedBy}</small><p>{m.question}</p></div><div className="doc-chat-answer"><small>AI practice helper</small><p>{m.answer}</p></div></div>)}</div><form onSubmit={e=>void chat(e)}><label className="sr-only" htmlFor="document-question">Question about this document</label><textarea id="document-question" value={question} onChange={e=>{setQuestion(e.target.value);messageId.current=crypto.randomUUID();}} maxLength={1200} rows={2} placeholder="Help me understand…" disabled={disabled||!!busy}/><button className="doc-primary" disabled={disabled||!!busy||!question.trim()||selected.processing}>{busy==='chat'?'Thinking…':'Ask the helper'}</button></form></section>}
        <div className="doc-revision-footer"><div><h3>Ready for another go?</h3><p>Keep this version and add your next attempt alongside it.</p></div><button className="doc-secondary" disabled={disabled||!!busy} onClick={revision}>Add a revision ↗</button></div>
      </>}</section></div>
    {scanner&&<Scanner onClose={()=>setScanner(false)} onUse={next=>{chooseFiles(next);setScanner(false);}}/>}
  </div>;
}
