"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {ChevronRightIcon,CheckSquareIcon,MessageIcon,TargetIcon} from '@/components/Icons';
import {documentRequest,fileBase64,validateDocumentFiles,analysisReadState,type LearnerDocument,type DocumentMessage} from '@/lib/documents';
import {prepareDocumentFiles} from '@/lib/document-photos';
import WorkSourceSelect from '@/components/WorkSourceSelect';
import {workContext,readWorkContext,workSources,type WorkSource} from '@/lib/work-source';
import {isStudentPreview} from '@/lib/student-preview';
import FeedbackText from '@/components/FeedbackText';
import ReviewTiming from '@/components/ReviewTiming';
import {documentGroups,documentMeta,documentContext,type DocumentRole} from '@/lib/document-groups';
import {savedWorkDate} from '@/lib/saved-writing';
import {getLearning,type LearningRecord} from '@/lib/learning';
import SentenceComparison from '@/components/SentenceComparison';
import WritingReviewArticle from '@/components/WritingReviewArticle';
import WritingAnalysis from './WritingAnalysis';
import {useReviewRefresh} from '@/lib/use-review-refresh';
const WordReader=dynamic(()=>import('@/components/WordReader'),{ssr:false});
const Scanner=dynamic(()=>import('@/components/DocumentScanner'),{ssr:false});
function DocIcon({camera=false}:{camera?:boolean}){return <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{camera?<><path d="M8 5l1-2h6l1 2h4a1 1 0 0 1 1 1v13H3V6a1 1 0 0 1 1-1z"/><circle cx="12" cy="12" r="4"/></>:<><path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/></>}</svg>}
const statusLabel=(d:LearnerDocument)=>d.feedback?(d.reviewPending?'Teacher feedback scheduled':'Rory’s feedback ready'):d.processing?'Reading your work':d.status==='ready'?'AI practice feedback':d.status==='error'?'Saved · reading needs a retry':'Saved · ready to read';
const dateLabel=(s:string)=>new Date(s).toLocaleDateString(undefined,{day:'numeric',month:'short'});
export default function DocumentsView({code,name,teacher=false,parent=false,documentId=''}:{code:string;name:string;teacher?:boolean;parent?:boolean;documentId?:string}){
  const preview=isStudentPreview(code),disabled=preview||parent;
  const [documents,setDocuments]=useState<LearnerDocument[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [documentRole,setDocumentRole]=useState<DocumentRole>('answer'),[relatedReview,setRelatedReview]=useState<LearningRecord|null>(null),[reviewChoices,setReviewChoices]=useState<LearningRecord[]>([]),[linkedWork,setLinkedWork]=useState(''),[linkedReview,setLinkedReview]=useState('');
  const [workSource,setWorkSource]=useState<WorkSource>('unspecified');
  const [photoPreviews,setPhotoPreviews]=useState<string[]>([]);
  const [files,setFiles]=useState<File[]>([]),[title,setTitle]=useState(''),[context,setContext]=useState(''),[parentId,setParentId]=useState(''),[scanner,setScanner]=useState(false),[busy,setBusy]=useState('');
  const [selected,setSelected]=useState<LearnerDocument|null>(null),[messages,setMessages]=useState<DocumentMessage[]>([]),[question,setQuestion]=useState(''),[feedback,setFeedback]=useState('');
  const [fileView,setFileView]=useState<{url:string;name:string;type:string;file:File}|null>(null),[selectedLoading,setSelectedLoading]=useState(false);
  const [analysisWatch,setAnalysisWatch]=useState<string|null>(null),analysisStarted=useRef(0),analysisSeen=useRef(false),analysisError=useRef('');
  const input=useRef<HTMLInputElement>(null),uploadForm=useRef<HTMLFormElement>(null),filePreview=useRef<HTMLDivElement>(null),uploadId=useRef(crypto.randomUUID()),messageId=useRef(crypto.randomUUID()),selectedId=useRef<string|null>(null),lastReviewed=useRef(''),fileUrl=useRef('');
  useEffect(()=>{const urls=files.map(file=>file.type.startsWith('image/')?URL.createObjectURL(file):'');setPhotoPreviews(urls);return()=>urls.filter(Boolean).forEach(url=>URL.revokeObjectURL(url));},[files]);
  useEffect(()=>{if(!files.length)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[files.length]);
  const rpc=useCallback((body:Record<string,unknown>)=>documentRequest(code,teacher,body),[code,teacher]);
  const refresh=useCallback(async()=>{const r=await rpc({action:'documents'});setLoaded(true);if(r.ok){setDocuments(r.documents||[]);if(teacher){const learning=await getLearning(code,true);if(learning.ok)setReviewChoices((learning.records||[]).filter(r=>r.body.writing));}}else setError(r.error||'Could not load saved documents.');},[rpc,teacher,code]);
  useEffect(()=>{void refresh();return()=>{if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);};},[refresh]);
  useEffect(()=>{if(fileView)filePreview.current?.scrollIntoView({behavior:'smooth',block:'center'});},[fileView]);
  const loadDocument=useCallback(async(id:string,initial=false)=>{
    if(initial){selectedId.current=id;setSelectedLoading(true);setSelected(null);setRelatedReview(null);setMessages([]);setError('');setQuestion('');messageId.current=crypto.randomUUID();lastReviewed.current='';if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);fileUrl.current='';setFileView(null);}
    const r=await rpc({action:'document',id});if(selectedId.current!==id)return;
    setSelectedLoading(false);if(r.ok&&r.document){setSelected(r.document);setRelatedReview(r.review||null);setLinkedWork(r.document.parentId||'');setLinkedReview(documentMeta(r.document.context).reviewId);setMessages(r.messages||[]);if(initial||lastReviewed.current!==r.document.reviewed){setFeedback(r.document.feedback);lastReviewed.current=r.document.reviewed;}setDocuments(ds=>ds.map(d=>d.id===id?{...d,...r.document}:d));}else setError(r.error||'Could not open that document.');
  },[rpc]);
  useEffect(()=>{const id=documentId||new URLSearchParams(window.location.search).get('document');if(id)void loadDocument(id,true);},[documentId,loadDocument]);
  useReviewRefresh(()=>{void refresh();if(selectedId.current)void loadDocument(selectedId.current);},documents.map(d=>d.feedbackAvailableAt));
  useEffect(()=>{if(!selected||analysisWatch!==selected.id)return;if(selected.processing)analysisSeen.current=true;
    const state=analysisReadState(selected,analysisSeen.current,analysisError.current);
    if(state==='ready'){setAnalysisWatch(null);setError('');setNotice('Sentence review ready.');}
    else if(state==='error'){setAnalysisWatch(null);setError(selected.error);setNotice('');}
  },[selected,analysisWatch]);
  useEffect(()=>{if(!selected||(!selected.processing&&analysisWatch!==selected.id&&busy!=='analyse'&&busy!=='chat'))return;const id=selected.id;let reading=false;
    const t=setInterval(async()=>{if(reading)return;if(analysisWatch===id&&Date.now()-analysisStarted.current>360000){setAnalysisWatch(null);setNotice('Your original is saved. Check for updates when you return.');return;}reading=true;try{await loadDocument(id);}finally{reading=false;}},6000);return()=>clearInterval(t);
  },[selected?.id,selected?.processing,analysisWatch,busy,loadDocument]);
  async function chooseFiles(next:File[]){if(disabled||busy||!next.length)return;setBusy('prepare');setError('');setNotice('Preparing clear upload copies…');try{const prepared=await prepareDocumentFiles(next);setFiles(prepared);uploadId.current=crypto.randomUUID();if(!title)setTitle(next.length===1?next[0].name.replace(/\.[^.]+$/,''):'Scanned work');setNotice(prepared.some((f,i)=>f!==next[i])?'Photos resized for upload. Your originals stay on your device. Check the words are clear before saving.':'');}catch(e){setError((e as Error).message);setNotice('');}finally{setBusy('');}}
  async function analyse(id:string){setBusy('analyse');setError('');analysisStarted.current=Date.now();analysisSeen.current=false;analysisError.current=selected?.error||'';setAnalysisWatch(id);setNotice('Reading the saved document. You can leave this page and come back to check it.');const r=await rpc({action:'documentAnalyse',id});setBusy('');if(!r.ok&&!r.offline){setAnalysisWatch(null);setError(r.error||'Your document is saved. The reading could not finish.');setNotice('');}else setNotice(r.pending||r.offline?'Still reading. The sentence review will appear automatically when ready.':'');await loadDocument(id);await refresh();}
  async function upload(e:React.FormEvent){e.preventDefault();if(disabled||busy)return;const problem=validateDocumentFiles(files);if(problem){setError(problem);return;}setBusy('upload');setError('');setNotice('Saving the file to this student’s profile…');try{const storedOnly=documentRole!=='answer'||files.some(f=>f.type.startsWith('audio/'));const encoded=await Promise.all(files.map(async f=>({name:f.name,type:f.type,data:await fileBase64(f)})));const r=await rpc({action:'documentUpload',id:uploadId.current,title:title.trim(),context:documentContext(workContext(workSource,context),documentRole),parentId,files:encoded});if(!r.ok||!r.received||!r.document)throw new Error(r.error||'The upload has not been confirmed. Keep this page open and retry to check the same upload.');const id=r.document.id;setFiles([]);setTitle('');setContext('');setWorkSource('unspecified');setDocumentRole('answer');setParentId('');uploadId.current=crypto.randomUUID();setBusy('');setNotice(storedOnly?'File saved with this work. You can read it here.':'Work saved. Preparing practice feedback…');await refresh();await loadDocument(id,true);if(!storedOnly)await analyse(id);}catch(e){setError((e as Error).message);setNotice('');setBusy('');}}
  async function chat(e:React.FormEvent){e.preventDefault();if(!selected||!question.trim()||busy||disabled)return;const id=selected.id;setBusy('chat');setError('');const r=await rpc({action:'documentChat',id,messageId:messageId.current,question:question.trim()});setBusy('');if(r.ok&&!r.pending){setQuestion('');messageId.current=crypto.randomUUID();}else setError(r.pending?'The helper is still working. Your question is kept here; check again in a moment.':r.error||'Could not confirm the reply. Your question is kept here.');await loadDocument(id);}
  async function publish(){if(!selected||!teacher||disabled)return;setBusy('review');setError('');const r=await rpc({action:'teacherDocumentReview',id:selected.id,feedback});setBusy('');if(r.ok){setNotice(r.document?.reviewPending?'Feedback approved and saved. It will appear automatically after the five-hour review window.':`Your feedback is now visible to ${name}.`);await loadDocument(selected.id);await refresh();}else setError(r.error||'Could not save your feedback.');}
  async function openFile(index:number){
    if(!selected)return;
    const id=selected.id;setBusy('file');setError('');
    try{
      const r=await rpc({action:'documentFile',id,index});
      if(selectedId.current!==id)return;
      if(!r.ok||!r.file)throw new Error(r.error||'Could not open this file.');
      const bytes=Uint8Array.from(atob(r.file.data),c=>c.charCodeAt(0));
      const file=new File([bytes],r.file.name,{type:r.file.type||'application/octet-stream'});
      const url=URL.createObjectURL(file);
      if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);
      fileUrl.current=url;setFileView({url,name:file.name,type:file.type,file});
    }catch(e){setError(e instanceof Error?e.message:'Could not open this file. Please try again.');}
    finally{setBusy('');}
  }
  async function shareFile(){
    if(!fileView)return;
    try{if(navigator.canShare?.({files:[fileView.file]})&&navigator.share){await navigator.share({files:[fileView.file],title:fileView.name});return;}}
    catch(e){if((e as Error).name==='AbortError')return;}
    const link=document.createElement('a');link.href=fileView.url;link.download=fileView.name;document.body.appendChild(link);link.click();link.remove();
  }
  function revision(){if(!selected)return;setParentId(group?.root.id||selected.id);setDocumentRole('answer');setTitle(`Revision: ${selected.title}`.slice(0,150));setContext(readWorkContext(documentMeta(selected.context).context).task);setWorkSource(readWorkContext(documentMeta(selected.context).context).source);setFiles([]);uploadId.current=crypto.randomUUID();uploadForm.current?.scrollIntoView({behavior:'smooth',block:'start'});setNotice('Add the revised work above. The earlier version will stay saved.');}
  const groups=documentGroups(documents),group=groups.find(g=>g.items.some(d=>d.id===selected?.id));
  async function linkSaved(){if(!selected||!teacher||disabled||busy)return;setBusy('link');setError('');const meta=documentMeta(selected.context),r=await rpc({action:'teacherDocumentLink',id:selected.id,parentId:linkedWork,context:documentContext(meta.context,meta.role,linkedReview)});setBusy('');if(r.ok){await refresh();await loadDocument(selected.id);setNotice('Saved work linked. The original files and feedback remain available.');}else setError(r.error||'Could not link this work.');}
  return <div className={`documents-space ${documentId?'doc-inline':''}`} >
    {!documentId&&<>
    <section className="doc-hero"><div><p className="doc-eyebrow">{teacher?`${name.toUpperCase()}’S LEARNING FILE`:'YOUR SAVED WORK'}</p><h1>{teacher?'Documents & feedback':'Documents'}</h1><p>{teacher?`Scan or upload work for ${name}. Originals, practice feedback and follow-up questions stay together here.`:'Scan or upload a page, then find the original and Rory’s feedback here.'}</p></div><div className="doc-paper-art" aria-hidden="true"><span className="doc-art-spark">✦</span><div><i/><i/><i/><b>one small<br/>step forward.</b><i/></div><span className="doc-art-badge">✓</span></div></section>
    {!teacher&&!parent&&<nav className="ux-route-grid" aria-label="Related work pages"><Link className="ux-route-card" href={`/s/${code}/homework/`}><CheckSquareIcon/><span><strong>Homework</strong><small>Return to the task</small></span><ChevronRightIcon/></Link><Link className="ux-route-card" href={`/s/${code}/progress/`}><MessageIcon/><span><strong>Feedback</strong><small>Rory’s next steps</small></span><ChevronRightIcon/></Link><Link className="ux-route-card" href={`/s/${code}/test-prep/`}><TargetIcon/><span><strong>Test prep</strong><small>Practice for a test</small></span><ChevronRightIcon/></Link></nav>}
    <ol className="doc-steps" aria-label="How it works"><li><span>1</span><div>Save your work<small>Scan pages or upload a file</small></div></li><li><span>2</span><div>Read & explore<small>AI suggestions and questions</small></div></li><li><span>3</span><div>Feedback & retry<small>Rory’s review, then your next draft</small></div></li></ol>
    {preview&&<p className="doc-notice">Student preview is read-only. Add documents from the teacher workspace.</p>}
    {!parent&&<form ref={uploadForm} className="doc-upload-card" onSubmit={e=>void upload(e)}>
      <div className="doc-upload-actions"><button type="button" className="doc-upload-option" disabled={disabled||!!busy} onClick={()=>setScanner(true)}><span><DocIcon camera/></span><strong>Scan pages</strong><small>Use your phone, iPad or laptop camera</small></button><button type="button" className="doc-upload-option" disabled={disabled||!!busy} onClick={()=>input.current?.click()}><span><DocIcon/></span><strong>Upload a document</strong><small>Photos up to 20 MB each · automatically resized</small></button><input ref={input} type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif,application/vnd.openxmlformats-officedocument.wordprocessingml.document,.docx,audio/webm,audio/mp4,audio/ogg,audio/mpeg" hidden onChange={e=>{void chooseFiles(Array.from(e.target.files||[]));e.target.value='';}}/></div>
      <p className="doc-muted">Choose up to six photos; large photos are resized automatically and your originals stay on your device. Word, PDF and audio files: up to 2.5 MB.</p>
      <p className="doc-privacy">Saved privately to {teacher?`${name}’s`:'your'} profile, visible to the student, parents and Rory. AI reads the file to offer practice suggestions; it does not assign a grade.</p>
      {(files.length>0||parentId)&&<div className="doc-upload-details">{parentId&&<p className="doc-notice">Added to saved work · originals stay saved <button type="button" className="doc-link" onClick={()=>setParentId('')}>Save as separate work</button></p>}<div className="doc-selected-files">{files.map((f,i)=><span key={`${i}-${f.name}`}><DocIcon/>{f.name} <small>{Math.ceil(f.size/1000)} KB</small>{photoPreviews[i]&&<img src={photoPreviews[i]} alt={`Upload copy of page ${i+1}`} style={{width:100,height:140,objectFit:"contain"}}/>}</span>)}</div><label>Title<input required maxLength={150} value={title} disabled={!!busy} onChange={e=>setTitle(e.target.value)} placeholder="e.g. My school blog — first draft"/></label><label>This file is<select value={documentRole} onChange={e=>setDocumentRole(e.target.value as DocumentRole)} disabled={!!busy}><option value="answer">Student writing / answer</option><option value="task">Task instructions / supporting material</option>{teacher&&<option value="review">Review / practice worksheet</option>}</select></label><label>Save with<select value={parentId} onChange={e=>{setParentId(e.target.value);const root=documents.find(d=>d.id===e.target.value);if(root)setWorkSource(readWorkContext(documentMeta(root.context).context).source);}} disabled={!!busy}><option value="">New piece of work</option>{groups.map(g=><option key={g.root.id} value={g.root.id}>{g.root.title}</option>)}</select></label><WorkSourceSelect value={workSource} onChange={setWorkSource} disabled={!!busy}/><label>School task or question <span className="doc-muted">(optional)</span><textarea value={context} maxLength={2000} rows={2} disabled={!!busy} onChange={e=>setContext(e.target.value)} placeholder="What were you asked to do? Add the task instructions or what you’d like help with."/></label><div className="doc-button-row"><button className="doc-primary" disabled={disabled||!!busy||!files.length||!title.trim()}>{busy==='upload'?'Saving work…':`Save ${teacher?`to ${name}’s profile`:'& read my work'}`}</button><button type="button" className="doc-secondary" disabled={!!busy} onClick={()=>{setFiles([]);setParentId('');setTitle('');setContext('');setWorkSource('unspecified');setDocumentRole('answer');}}>Cancel</button></div></div>}
    </form>}
    </>}
    {error&&<div className="doc-error" role="alert">{error}</div>}{notice&&<p className="doc-notice" role="status">{notice}</p>}
    <div className="doc-workspace">{!documentId&&<section className="doc-library"><header><h2>Saved work <span>{groups.length}</span></h2><button className="doc-link" onClick={()=>{setError('');void refresh();}}>Refresh</button></header>{!loaded?<p role="status" className="doc-muted">Opening your learning file…</p>:!documents.length?<div className="doc-empty"><DocIcon/><h3>Every draft starts somewhere.</h3><p>Scan a handwritten page or add a PDF. You’ll find it here whenever you need it.</p></div>:<div className="doc-list">{groups.map(g=>{const d=g.root,active=g.items.some(item=>selectedId.current===item.id);return <button key={d.id} className={`doc-list-item ${active?'is-selected':''}`} aria-pressed={active} disabled={!!busy} onClick={()=>void loadDocument(d.id,true)}><span className="doc-list-icon"><DocIcon/></span><div><strong>{d.title}</strong><small>{workSources[readWorkContext(documentMeta(d.context).context).source]} · {dateLabel(savedWorkDate(d))} · {g.items.length===1?'1 saved item':`${g.items.length} linked items`}</small><span className={`doc-status ${g.items.some(x=>x.feedback)?'reviewed':''}`}>{g.items.some(x=>x.feedback)?'Rory’s feedback ready':statusLabel(d)}</span></div><span aria-hidden="true">↗</span></button>})}</div>}</section>}
      <section className="doc-detail" aria-label="Selected document">{selectedLoading?<p role="status">Opening document…</p>:!selected?<div className="doc-detail-empty"><span aria-hidden="true">✧</span><h2>A place to work things out.</h2><p>Choose a saved document to see the original, explore the feedback and ask a question.</p></div>:<>
        <header className="doc-detail-heading"><div><p className="doc-eyebrow">{documentMeta(selected.context).role==='review'?'SAVED REVIEW':documentMeta(selected.context).role==='task'?'TASK MATERIAL':selected.parentId?'REVISED WORK':'SAVED ORIGINAL'}</p><h2>{selected.title}</h2><p className="doc-eyebrow">{workSources[readWorkContext(documentMeta(selected.context).context).source]}</p><p className="doc-muted">Added by {selected.uploadedBy} · {dateLabel(selected.created)}</p></div><button className="doc-link" disabled={!!busy} onClick={()=>void loadDocument(selected.id)}>Check for updates</button></header>
        {readWorkContext(documentMeta(selected.context).context).task&&<p className="doc-task-context">{readWorkContext(documentMeta(selected.context).context).task}</p>}{selected.parentId&&<button className="doc-link" onClick={()=>void loadDocument(selected.parentId,true)}>← Open earlier version</button>}
        {group&&group.items.length>1&&<nav className="doc-group-items" aria-label="Work and attached files"><h3>One piece of work</h3>{group.items.map(d=><button key={d.id} className="doc-secondary" aria-pressed={d.id===selected.id} disabled={!!busy} onClick={()=>void loadDocument(d.id,true)}>{documentMeta(d.context).role==='review'?'Review / worksheet':documentMeta(d.context).role==='task'?'Task material':d.id===group.root.id?'Original writing':'Revised answer'} · {d.title}</button>)}</nav>}
        {relatedReview&&<><WritingReviewArticle record={relatedReview}/>{teacher&&<WritingAnalysis record={relatedReview} code={code} teacher onSaved={async()=>{await loadDocument(selected.id);}}/>}</>}
        <div className="doc-originals">{selected.files.map(f=><button key={f.index} className="doc-secondary" disabled={!!busy} onClick={()=>void openFile(f.index)}><DocIcon/>{busy==='file'?'Opening file…':`Open ${selected.files.length>1?`page ${f.index+1}`:'original'}`}</button>)}</div>
        {fileView&&<div ref={filePreview} className="doc-file-preview"><div><strong>{fileView.name}</strong><div className="doc-button-row"><button type="button" className="doc-link" onClick={()=>void shareFile()}>Download original</button><button type="button" className="doc-link" onClick={()=>{setFileView(null);if(fileUrl.current)URL.revokeObjectURL(fileUrl.current);fileUrl.current='';}}>Close preview</button></div></div>{fileView.type==='application/pdf'?<iframe src={fileView.url} title="Original PDF"/>:fileView.type.startsWith('image/')?<img src={fileView.url} alt="Original uploaded work"/>:fileView.type.startsWith('audio/')?<audio controls src={fileView.url} aria-label="Original speaking recording"/>:<WordReader file={fileView.file}/>}</div>}
        {!relatedReview&&(selected.analysis&&documentMeta(selected.context).role==='answer'?<>
          <div className="doc-analysis-heading"><span aria-hidden="true">✦</span><div><h3>Let’s look at your work</h3><p>AI practice feedback · {selected.analysis.model||'model not recorded'} · check against the original</p></div></div><p className="doc-summary"><FeedbackText text={selected.analysis.summary}/></p>
          {(selected.analysis.coverage!=='complete'||selected.analysis.uncertainties.length>0)&&<div className="doc-reading-note"><strong>{selected.analysis.coverage==='unreadable'?'A clearer scan is needed':selected.analysis.coverage==='partial'?'Some parts could not be read':'Check these readings'}</strong>{selected.analysis.uncertainties.map((s,i)=><p key={i}>{s}</p>)}<p>Unclear handwriting is not treated as a language mistake.</p></div>}
          <details className="doc-transcript"><summary>Read the transcription <span>Original wording · possible reading errors</span></summary><p>{selected.analysis.transcription||'No readable text was found.'}</p></details>
          {selected.analysis.strengths.length>0&&<div className="doc-strengths"><h3>What’s working</h3><ul>{selected.analysis.strengths.map((s,i)=><li key={i}><FeedbackText text={s}/></li>)}</ul></div>}
          {selected.analysis.writing?<SentenceComparison writing={selected.analysis.writing}/>:<div className="doc-reading-note"><p>This older analysis has excerpts. Generate a full sentence review from the saved original.</p>{!parent&&<button className="doc-primary" disabled={disabled||!!busy||selected.processing} onClick={()=>void analyse(selected.id)}>Generate sentence review</button>}</div>}
          {selected.analysis.corrections.length>0&&<div className="doc-corrections"><h3>A few useful changes</h3>{selected.analysis.corrections.map((c,i)=><article key={i}><div><small>YOUR WORDS</small><p>{c.original}</p></div><span aria-hidden="true">→</span><div><small>TRY THIS</small><p><FeedbackText text={c.suggestion}/></p></div><p><FeedbackText text={c.explanation}/></p></article>)}</div>}
          {selected.analysis.retry&&<div className="doc-retry"><span aria-hidden="true">↺</span><div><h3>Your next small step</h3><p><FeedbackText text={selected.analysis.retry}/></p></div></div>}
        </>:documentMeta(selected.context).role!=='answer'?<p className="doc-reading-note">Saved supporting material. Open it above to read inside the app.</p>:<div className="doc-reading-note"><h3>{selected.processing?'Reading the saved pages…':'Your original is saved.'}</h3><p>{selected.processing?'The reading may take a minute or two. You can return later to see the result.':selected.error||'Read the document to get practice feedback and ask questions about it.'}</p>{!parent&&!selected.files.some(f=>f.type.startsWith('audio/'))&&<button className="doc-primary" disabled={disabled||!!busy||selected.processing} onClick={()=>void analyse(selected.id)}>{selected.status==='error'?'Retry reading':'Read & analyse'}</button>}{selected.files.some(f=>f.type.startsWith('audio/'))&&<p>This recording is saved for Rory to review.</p>}</div>)}
        <div className="doc-teacher-feedback"><p className="doc-eyebrow">RORY’S REVIEW</p>{teacher?<><h3>Your feedback for {name}</h3><label className="sr-only" htmlFor="document-feedback">Teacher feedback</label><textarea id="document-feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} maxLength={6000} rows={5} placeholder="Add your reviewed feedback and the next step…"/><p className="doc-muted">Key instruction words are highlighted for the student. Add **double stars** around another short phrase to highlight it.</p><button className="doc-primary" disabled={disabled||!!busy||!feedback.trim()||feedback===selected.feedback} onClick={()=>void publish()}>Approve feedback for {name}</button><p className="doc-muted">AI suggestions stay separately labelled.</p></>:selected.feedback?<><h3>Feedback from Rory</h3><p className="doc-preserve"><FeedbackText text={selected.feedback}/></p><small>Reviewed {dateLabel(selected.reviewed)}</small></>:<><h3>Waiting for Rory’s review</h3><p>The suggestions above are AI practice advice, not Rory’s review.</p></>}{selected.feedbackAvailableAt&&<ReviewTiming availableAt={selected.feedbackAvailableAt} teacher={teacher}/>}</div>
        {selected.analysis&&<section className="doc-chat"><h3>Ask about this document <span>AI helper</span></h3><p className="doc-muted">Ask for an explanation, a hint or a practice example. This conversation is saved with the work and visible to Rory and {teacher?name:'you'}.</p>{!messages.length&&!parent&&<div className="doc-question-chips">{['Explain one change','Give me a hint for my retry','What should I practise next?'].map(q=><button key={q} className="doc-secondary" disabled={disabled||!!busy} onClick={()=>{setQuestion(q);messageId.current=crypto.randomUUID();}}>{q}</button>)}</div>}<div className="doc-conversation" aria-live="polite">{messages.map(m=><div key={m.id}><div className="doc-chat-question"><small>{m.askedBy}</small><p>{m.question}</p></div><div className="doc-chat-answer"><small>AI practice helper</small><p>{m.answer}</p></div></div>)}</div>{!parent&&<form onSubmit={e=>void chat(e)}><label className="sr-only" htmlFor="document-question">Question about this document</label><textarea id="document-question" value={question} onChange={e=>{setQuestion(e.target.value);messageId.current=crypto.randomUUID();}} maxLength={1200} rows={2} placeholder="Help me understand…" disabled={disabled||!!busy}/><button className="doc-primary" disabled={disabled||!!busy||!question.trim()||selected.processing}>{busy==='chat'?'Thinking…':'Ask the helper'}</button></form>}</section>}
        {teacher&&<details className="doc-transcript"><summary>Organise this saved work</summary><label>Belongs to<select value={linkedWork} onChange={e=>setLinkedWork(e.target.value)}><option value="">Separate piece of work</option>{groups.filter(g=>g.root.id!==selected.id&&!g.items.some(d=>d.id===selected.id)).map(g=><option key={g.root.id} value={g.root.id}>{g.root.title}</option>)}{selected.parentId&&<option value={selected.parentId}>Current linked work</option>}</select></label><label>Writing review<select value={linkedReview} onChange={e=>setLinkedReview(e.target.value)}><option value="">No linked review</option>{reviewChoices.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><button className="doc-secondary" disabled={!!busy} onClick={()=>void linkSaved()}>Save links</button></details>}
        {!parent&&!documentId&&<div className="doc-revision-footer"><div><h3>Ready for another go?</h3><p>Keep this version and add your next attempt alongside it.</p></div><div className="doc-button-row"><button className="doc-secondary" disabled={disabled||!!busy} onClick={revision}>Add a revised answer</button>{teacher&&<button className="doc-secondary" disabled={disabled||!!busy} onClick={()=>{revision();setDocumentRole('review');setTitle('Review / practice worksheet');}}>Add a review or worksheet</button>}</div></div>}
      </>}</section></div>
    {scanner&&<Scanner onClose={()=>setScanner(false)} onUse={next=>{chooseFiles(next);setScanner(false);}}/>}
  </div>;
}
