"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {getLearning,replyLearning,saveLearning,type LearningBody,type LearningKind,type LearningRecord,type LearningReply,type WritingComparison} from '@/lib/learning';
import {isStudentPreview} from '@/lib/student-preview';
import FeedbackText from '@/components/FeedbackText';
import SpeakingAudioReview from './SpeakingAudioReview';
import WritingAnalysis,{ComparisonFields} from './WritingAnalysis';

const labels:Record<LearningKind,string>={homework:'Homework review',test:'Test preparation',speaking:'Speaking',lesson:'Lesson notes'};
const kinds:LearningKind[]=['homework','test','speaking','lesson'];
const ratingLabels:Record<string,string>={fluency:'Flow',accuracy:'Grammar and vocabulary',organisation:'Development',interaction:'Interaction',intelligibility:'Intelligibility'};
const split=(s:string)=>s.split('\n').map(x=>x.trim()).filter(Boolean);
const join=(xs?:string[])=>xs?.join('\n')||'';
const box='w-full rounded-xl border border-black/10 bg-white p-3 text-sm text-navy outline-none focus:border-indigo-500 dark:border-white/15 dark:bg-navy dark:text-cream';
const card='rounded-card bg-surface p-5 shadow-card dark:bg-navy-raised dark:shadow-card-dark';
const button='rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40';
const today=()=>new Date().toISOString().slice(0,10);

export default function LearningView({code,name,mode,initialFilter='all',showHeader=true}:{code:string;name:string;mode:'student'|'parent'|'teacher';initialFilter?:'all'|LearningKind;showHeader?:boolean}) {
  const [records,setRecords]=useState<LearningRecord[]>([]),[replies,setReplies]=useState<LearningReply[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [filter,setFilter]=useState<'all'|LearningKind>(initialFilter);
  const [kind,setKind]=useState<LearningKind>('homework'),[title,setTitle]=useState(''),[date,setDate]=useState(today()),[visibility,setVisibility]=useState<'shared'|'teacher'>('shared');
  const [summary,setSummary]=useState(''),[strengths,setStrengths]=useState(''),[targets,setTargets]=useState(''),[nextStep,setNextStep]=useState(''),[evidenceType,setEvidenceType]=useState(''),[source,setSource]=useState('');
  const [studentNotes,setStudentNotes]=useState(''),[lessonPoints,setLessonPoints]=useState(''),[original,setOriginal]=useState(''),[corrected,setCorrected]=useState(''),[model,setModel]=useState(''),[practice,setPractice]=useState('');
  const [comparisons,setComparisons]=useState<WritingComparison[]>([]);
  const [worked,setWorked]=useState(''),[improve,setImprove]=useState(''),[plan,setPlan]=useState(''),[busy,setBusy]=useState(false),[answer,setAnswer]=useState<Record<string,string>>({});
  const [ratings,setRatings]=useState<Record<string,number|null>>({});
  const ids=useRef<Record<string,string>>({});
  const disabled=mode==='parent'||isStudentPreview(code);
  const checkpoints=records.filter(r=>r.kind==='speaking'&&r.body.ratings&&Object.values(r.body.ratings).some(v=>v!=null)).sort((a,b)=>a.date.localeCompare(b.date));
  const refresh=useCallback(async()=>{const r=await getLearning(code,mode==='teacher');setLoading(false);if(r.ok){setRecords(r.records||[]);setReplies(r.replies||[]);setError('');}else setError(r.error||'Could not open the learning record.');},[code,mode]);
  useEffect(()=>{void refresh();},[refresh]);
  async function create(e:React.FormEvent){e.preventDefault();if(mode!=='teacher'||busy)return;setBusy(true);setError('');setMessage('');
    const body:LearningBody={summary:summary.trim(),strengths:split(strengths),targets:split(targets),nextStep:nextStep.trim(),evidenceType:evidenceType.trim(),source:source.trim(),studentNotes:studentNotes.trim(),lessonPoints:lessonPoints.trim(),ratings,tutorPrivate:{worked:worked.trim(),improve:improve.trim(),plan:plan.trim()}};
    if(kind==='homework'||kind==='test')body.writing={original:original.trim(),corrected:corrected.trim(),model:model.trim(),comparisons:comparisons.map(r=>({original:r.original.trim(),corrected:r.corrected.trim(),improved:r.improved.trim(),note:r.note.trim()})).filter(r=>r.original||r.corrected||r.improved||r.note),practice:split(practice)};
    const result=await saveLearning(code,{id:crypto.randomUUID(),date,kind,title:title.trim(),visibility,body});setBusy(false);
    if(result.ok){setMessage('Review saved to the learning record.');setTitle('');setSummary('');setStrengths('');setTargets('');setNextStep('');setStudentNotes('');setLessonPoints('');setOriginal('');setCorrected('');setModel('');setPractice('');setComparisons([]);setWorked('');setImprove('');setPlan('');setRatings({});await refresh();}
    else setError(result.error||'Could not save this review.');
  }
  async function submit(id:string){const value=(answer[id]||'').trim();if(!value||busy||disabled)return;setBusy(true);setError('');const key=ids.current[id]||crypto.randomUUID();ids.current[id]=key;const r=await replyLearning(code,id,key,value);setBusy(false);if(r.ok&&r.received){delete ids.current[id];setAnswer(a=>({...a,[id]:''}));setMessage('Your answer is saved. Rory can review it.');await refresh();}else setError(r.error||'Could not confirm your answer. Keep it here and try again.');}
  return <div className="learning-record space-y-5 py-4 text-navy dark:text-cream">
    {showHeader&&<header className={card}><p className="text-xs font-bold uppercase tracking-widest text-indigo-600 dark:text-amber">RORY’S REVIEWS</p><h2 className="display mt-1 text-2xl">{mode==='teacher'?`${name}'s reviews`:mode==='parent'?`${name}'s learning`:'Feedback and next steps'}</h2><p className="mt-2 text-sm text-navy-soft dark:text-navy-mist">Writing, speaking, lessons and school tests. Open an entry to see what worked and what to try next.</p></header>}
    {mode==='teacher'&&<details className={card}><summary className="cursor-pointer font-bold">Add a review or lesson note</summary><form onSubmit={create} className="mt-4 space-y-3">
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Type<select className={box} value={kind} onChange={e=>setKind(e.target.value as LearningKind)}>{kinds.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label className="text-sm">Date<input className={box} type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div>
      <label className="block text-sm">Title<input className={box} required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Press freedom essay review"/></label>
      <label className="block text-sm">Who can see this?<select className={box} value={visibility} onChange={e=>setVisibility(e.target.value as 'shared'|'teacher')}><option value="shared">Student, parents and Rory</option><option value="teacher">Only Rory</option></select></label>
      <label className="block text-sm">Summary<textarea className={box} rows={2} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="What this review found"/></label>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Strengths · one per line<textarea className={box} rows={3} value={strengths} onChange={e=>setStrengths(e.target.value)}/></label><label className="text-sm">Priorities · one per line<textarea className={box} rows={3} value={targets} onChange={e=>setTargets(e.target.value)}/></label></div>
      <label className="block text-sm">Next independent step<textarea className={box} rows={2} value={nextStep} onChange={e=>setNextStep(e.target.value)}/></label>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Evidence type<input className={box} value={evidenceType} onChange={e=>setEvidenceType(e.target.value)} placeholder="Handwritten page, audio, transcript…"/></label><label className="text-sm">School task or lesson ID<input className={box} value={source} onChange={e=>setSource(e.target.value)}/></label></div>
      {(kind==='speaking'||kind==='lesson')&&<fieldset className="rounded-xl border border-black/10 p-3 dark:border-white/15"><legend className="px-1 font-semibold">Optional classroom ratings · 1 to 4</legend><p className="mb-2 text-xs">1 = needs support; 4 = consistently effective for this task. Leave unobserved skills blank. These are not CEFR grades.</p><div className="grid gap-2 sm:grid-cols-2">{Object.entries(ratingLabels).map(([key,label])=><label key={key} className="text-sm">{label}<select className={box} value={ratings[key]??''} onChange={e=>setRatings(v=>({...v,[key]:e.target.value?Number(e.target.value):null}))}><option value="">Not observed</option>{[1,2,3,4].map(n=><option key={n} value={n}>{n} / 4</option>)}</select></label>)}</div></fieldset>}
      <label className="block text-sm">Student notes<textarea className={box} rows={2} value={studentNotes} onChange={e=>setStudentNotes(e.target.value)}/></label><label className="block text-sm">Lesson points<textarea className={box} rows={2} value={lessonPoints} onChange={e=>setLessonPoints(e.target.value)}/></label>
      {(kind==='homework'||kind==='test')&&<details className="rounded-xl border border-black/10 p-3 dark:border-white/15"><summary className="cursor-pointer font-semibold">Writing analysis and practice</summary><div className="mt-3 space-y-3"><label className="block text-sm">Original wording<textarea className={box} rows={5} value={original} onChange={e=>setOriginal(e.target.value)}/></label><label className="block text-sm">Corrected version<textarea className={box} rows={5} value={corrected} onChange={e=>setCorrected(e.target.value)}/></label><label className="block text-sm">More developed model<textarea className={box} rows={5} value={model} onChange={e=>setModel(e.target.value)}/></label><ComparisonFields rows={comparisons} onChange={setComparisons}/><label className="block text-sm">Practice questions · one per line<textarea className={box} rows={4} value={practice} onChange={e=>setPractice(e.target.value)}/></label></div></details>}
      <details className="rounded-xl border border-black/10 p-3 dark:border-white/15"><summary className="cursor-pointer font-semibold">Tutor reflection · only Rory sees this</summary><div className="mt-3 space-y-3"><label className="block text-sm">What worked<textarea className={box} rows={2} value={worked} onChange={e=>setWorked(e.target.value)}/></label><label className="block text-sm">What to improve<textarea className={box} rows={2} value={improve} onChange={e=>setImprove(e.target.value)}/></label><label className="block text-sm">What I will change next time<textarea className={box} rows={2} value={plan} onChange={e=>setPlan(e.target.value)}/></label></div></details>
      <button className={button} disabled={busy||!title.trim()}>{busy?'Saving…':'Save review'}</button>
    </form></details>}
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="rounded-xl bg-green-50 p-3 text-sm text-green-800">{message}</p>}
    <nav className="learning-filters flex flex-wrap gap-2" aria-label="Filter learning records">{(['all',...kinds] as const).map(k=><button key={k} type="button" aria-pressed={filter===k} onClick={()=>setFilter(k)} className={`rounded-full border px-3 py-2 text-sm ${filter===k?'border-indigo-600 bg-indigo-600 text-white':'border-black/15 dark:border-white/20'}`}>{k==='all'?'All':labels[k]}</button>)}</nav>
    {checkpoints.length>0&&<section className={card}><h3 className="font-bold">Speaking checkpoints</h3><p className="mt-1 text-xs text-navy-soft dark:text-navy-mist">Rory’s task based observations. Compare similar tasks and support levels before reading a change as progress.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="pr-3">Date</th>{Object.entries(ratingLabels).map(([key,label])=><th key={key} className="pr-3">{label}</th>)}</tr></thead><tbody>{checkpoints.slice(-4).map(r=><tr key={r.id} className="border-t border-black/10 dark:border-white/10"><td className="py-2 pr-3">{r.date}</td>{Object.keys(ratingLabels).map(key=><td key={key} className="pr-3">{r.body.ratings?.[key]??'—'}</td>)}</tr>)}</tbody></table></div><p className="mt-2 text-xs">Scale: 1–4. A dash means not observed.</p></section>}
    {loading?<p>Opening the learning record…</p>:!records.length?<p className={card}>No reviews yet. New work and lesson notes will appear here.</p>:!records.some(r=>filter==='all'||r.kind===filter)?<p className={card}>Nothing in this area yet.</p>:<div className="space-y-4">{records.filter(r=>filter==='all'||r.kind===filter).map(r=>{const b=r.body,w=b.writing,rs=replies.filter(x=>x.reviewId===r.id);return <article key={r.id} className={`${card} learning-kind-${r.kind}`}>
      <div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-indigo-100 px-2 py-1 font-bold text-indigo-800 dark:bg-indigo-900 dark:text-indigo-100">{labels[r.kind]}</span><span>{r.date}</span>{r.visibility==='teacher'&&<span className="rounded-full bg-amber/20 px-2 py-1">Rory only</span>}</div><h3 className="mt-2 text-xl font-bold">{r.title}</h3>{b.summary&&<p className="mt-2 whitespace-pre-wrap text-sm"><FeedbackText text={b.summary}/></p>}
      {(b.evidenceType||b.source)&&<p className="mt-2 text-xs text-navy-soft dark:text-navy-mist">{b.evidenceType}{b.source&&` · ${b.source}`}</p>}
      {!!b.strengths?.length&&<div className="mt-4"><h4 className="font-semibold">What’s working</h4><ul className="ml-5 list-disc text-sm">{b.strengths.map((x,i)=><li key={i}><FeedbackText text={x}/></li>)}</ul></div>}
      {!!b.targets?.length&&<div className="mt-4"><h4 className="font-semibold">Focus next</h4><ul className="ml-5 list-disc text-sm">{b.targets.map((x,i)=><li key={i}><FeedbackText text={x}/></li>)}</ul></div>}
      {b.nextStep&&<p className="mt-4 rounded-xl bg-indigo-50 p-3 text-sm dark:bg-navy"><strong>Next try:</strong> <FeedbackText text={b.nextStep}/></p>}
      {b.ratings&&Object.values(b.ratings).some(v=>v!=null)&&<div className="mt-4"><h4 className="font-semibold">Classroom checkpoint</h4><p className="text-xs text-navy-soft dark:text-navy-mist">Rory’s task based ratings, not a CEFR grade.</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(b.ratings).filter(([,v])=>v!=null).map(([k,v])=><span key={k} className="rounded-full bg-black/5 px-3 py-1 text-xs dark:bg-white/10">{ratingLabels[k]||k}: {v}/4</span>)}</div></div>}
      {w&&(w.original||w.corrected||w.model||w.practice?.length||w.comparisons?.length)?<WritingAnalysis key={`${r.id}-${r.created}`} record={r} code={code} teacher={mode==='teacher'} onSaved={refresh}/>:null}
      {b.transcript&&<details className="mt-4 rounded-xl border border-black/10 p-3 dark:border-white/15"><summary className="cursor-pointer font-semibold">Conversation transcript</summary><p className="mt-2 whitespace-pre-wrap text-sm"><FeedbackText text={b.transcript}/></p><p className="mt-2 text-xs">Captions may contain errors. Pronunciation and pace need an audio sample.</p></details>}
      {b.aiAnalysis&&<div className="mt-4 rounded-xl bg-indigo-50 p-3 text-sm dark:bg-navy"><strong>AI practice feedback · Rory has not reviewed this</strong><p className="mt-1 whitespace-pre-wrap"><FeedbackText text={b.aiAnalysis}/></p></div>}
      {b.audioDocumentId&&<SpeakingAudioReview code={code} name={name} mode={mode} record={r} onSaved={refresh}/>}
      {(b.studentNotes||b.lessonPoints)&&<div className="mt-4 space-y-2 text-sm">{b.studentNotes&&<p><strong>Student notes:</strong> {b.studentNotes}</p>}{b.lessonPoints&&<p><strong>Lesson points:</strong> {b.lessonPoints}</p>}</div>}
      {mode==='teacher'&&b.tutorPrivate&&(b.tutorPrivate.worked||b.tutorPrivate.improve||b.tutorPrivate.plan)&&<div className="mt-4 rounded-xl border border-amber/50 p-3 text-sm"><strong>Your teaching reflection · private</strong>{b.tutorPrivate.worked&&<p>Worked: {b.tutorPrivate.worked}</p>}{b.tutorPrivate.improve&&<p>Improve: {b.tutorPrivate.improve}</p>}{b.tutorPrivate.plan&&<p>Next lesson: {b.tutorPrivate.plan}</p>}</div>}
      {rs.length>0&&<div className="mt-4"><h4 className="font-semibold">Answers and revisions</h4>{rs.map(x=><div key={x.id} className="mt-2 rounded-xl bg-black/5 p-3 text-sm dark:bg-white/5"><small>{new Date(x.created).toLocaleDateString()} · {x.author}</small><p className="mt-1 whitespace-pre-wrap">{x.answer}</p></div>)}</div>}
      {mode==='student'&&r.visibility==='shared'&&(r.kind==='homework'||r.kind==='test'||r.kind==='lesson')&&<div className="mt-4 border-t border-black/10 pt-4 dark:border-white/10"><h4 className="font-semibold">Write your answer in the app</h4><textarea className={`${box} mt-2`} rows={5} maxLength={12000} disabled={disabled||busy} value={answer[r.id]||''} onChange={e=>setAnswer(a=>({...a,[r.id]:e.target.value}))} placeholder="Try the task in your own words. You can add another answer after feedback."/><div className="mt-2 flex flex-wrap gap-2"><button className={button} disabled={disabled||busy||!answer[r.id]?.trim()} onClick={()=>void submit(r.id)}>Save answer</button>{(r.kind==='homework'||r.kind==='test')&&<a className="rounded-xl border border-indigo-300 px-4 py-2.5 text-sm font-semibold" href="/resources/writing-review-template.docx" download>Download worksheet</a>}<Link className="rounded-xl border border-indigo-300 px-4 py-2.5 text-sm font-semibold" href={`/s/${code}/documents/`}>Upload a completed file</Link></div><p className="mt-2 text-xs text-navy-soft dark:text-navy-mist">Word, PDF or photos can be saved in My documents. Rory and your parents can view the saved work.</p></div>}
    </article>;})}</div>}
    {mode==='parent'&&<p className="text-sm text-navy-soft dark:text-navy-mist">This view is read only. Ask {name} to add a revision in the student app.</p>}
  </div>;
}
