"use client";
import {useEffect,useState} from 'react';
import {getLearning,type LearningRecord} from '@/lib/learning';
export default function TeachingProgress({students,onOpen}:{students:{code:string;name:string}[];onOpen:(code:string)=>void}){
 const [entries,setEntries]=useState<{code:string;name:string;record:LearningRecord}[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;Promise.all(students.map(async s=>({s,result:await getLearning(s.code,true)}))).then(all=>{if(!live)return;setEntries(all.flatMap(({s,result})=>(result.records||[]).filter(r=>r.kind==='lesson'&&r.body.tutorPrivate).map(record=>({code:s.code,name:s.name,record}))));setLoading(false);});return()=>{live=false;};},[students]);
 const lessons=entries.length,plans=entries.filter(e=>e.record.body.tutorPrivate?.plan),recent=[...entries].sort((a,b)=>b.record.date.localeCompare(a.record.date)).slice(0,3);
 return <section className="re-card mt-6"><p className="teacher-eyebrow">YOUR TEACHING PROGRESS</p><h2 className="mt-1 text-xl font-bold">What you tried and what changes next</h2><p className="mt-2 text-sm text-navy-soft dark:text-navy-mist">Private lesson reflections across students. Add one after each visit to see your teaching develop over time.</p>{loading?<p className="mt-4 text-sm">Opening lesson notes…</p>:<><div className="mt-4 flex gap-5 text-sm"><span><strong className="text-2xl">{lessons}</strong><br/>lessons reflected on</span><span><strong className="text-2xl">{plans.length}</strong><br/>next lesson changes recorded</span></div>{recent.length?<ul className="mt-4 space-y-3">{recent.map(e=><li key={e.record.id} className="rounded-xl bg-black/5 p-3 text-sm dark:bg-white/5"><button className="font-bold underline" onClick={()=>onOpen(e.code)}>{e.name} · {e.record.date}</button>{e.record.body.tutorPrivate?.worked&&<p className="mt-1">Worked: {e.record.body.tutorPrivate.worked}</p>}{e.record.body.tutorPrivate?.plan&&<p>Next time: {e.record.body.tutorPrivate.plan}</p>}</li>)}</ul>:<p className="mt-4 text-sm">No lesson reflections yet. Open a student’s Learning reviews to record what worked and what you will change.</p>}</>}</section>;
}
