"use client";
import {request,savedSession} from '@/lib/api';
import {useEffect,useState} from 'react';
import {rowToAssignment,type Progress,type Assignment,type Submission,type AssignmentsResult,type Submissions} from '@/lib/remote';
import {getLearning,saveLearning,type LearningRecord} from '@/lib/learning';
import {dashboardSettings,activityMetrics,homeworkMetrics,assessedLessons,lessonComparisons,readCheckpoint,checkpointResult,checkpointChange,viennaDay,type DashboardSettings,type Checkpoint,type Requirement} from '@/lib/teacher-metrics';
import {vocabularyCoverage} from '@/lib/vocabulary-coverage';
import {readLessonAssessment} from '@/lib/lesson-assessment';
import {readableDate} from '@/lib/clarity';
import type {Unit} from '@/lib/types';
import LessonAssessmentPanel from '@/components/LessonAssessmentPanel';
const box='mt-1 w-full rounded-lg border border-black/15 bg-transparent p-2 dark:border-white/20';
const emptySettings:DashboardSettings={version:1,requirements:{},schoolContext:''};
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="insight-metric"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>;}
export default function TeacherInsights({code,name,unit,onReview,onNotes}:{code:string;name:string;unit:Unit|null;onReview:()=>void;onNotes:()=>void}){
 const [records,setRecords]=useState<LearningRecord[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[progress,setProgress]=useState<Progress|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[days,setDays]=useState(30),[settings,setSettings]=useState<DashboardSettings>(emptySettings),[savedSettings,setSavedSettings]=useState<DashboardSettings>(emptySettings),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function refresh(){setLoading(true);setError('');try{const [l,a,s,p]=await Promise.all([getLearning(code,true),request<AssignmentsResult>({action:'assignments',code,session:savedSession('__teacher__')?.token||''}),request<Submissions>({action:'submissions',code,session:savedSession('__teacher__')?.token||''}),request<Progress>({action:'progress',code,session:savedSession('__teacher__')?.token||''})]);if(!l.ok||!a.ok||!s.ok||!p.ok)throw Error(l.error||a.error||s.error||p.error||'Some saved records could not be loaded.');setRecords(l.records||[]);setAssignments((a.assignments?.rows||[]).map(rowToAssignment));setSubmissions(s.submissions||[]);setProgress(p);const config=l.records?.find(r=>r.id==='teacher-dashboard-settings')?.body.tutorPrivate?.dashboardSettings;const value=dashboardSettings(config);setSettings(value);setSavedSettings(value);}catch(e){setError(e instanceof Error?e.message:'Could not open saved records.');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[code]);
 async function saveSettings(){setBusy(true);setMessage('');try{const result=await saveLearning(code,{id:'teacher-dashboard-settings',date:viennaDay(),kind:'test',title:'Private dashboard settings',visibility:'teacher',body:{tutorPrivate:{dashboardSettings:settings}}});if(!result.ok)throw Error(result.error||'Could not save settings.');setSavedSettings(settings);setMessage('Requirements and school context saved privately.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save settings.');}finally{setBusy(false);}}
 if(loading)return <p role="status" className="insight-loading">Opening homework, recorded lessons and saved activity…</p>;
 if(error)return <div role="alert" className="re-card"><p>{error}</p><button className="re-button mt-3" onClick={()=>void refresh()}>Retry dashboard</button></div>;
 const today=viennaDay(),activity=activityMetrics(records,submissions,progress,days,today),items=homeworkMetrics(code,unit,assignments,submissions,records,settings,today),required=items.filter(x=>x.requirement==='required'),received=required.filter(x=>x.received||x.reviewed).length,reviewed=required.filter(x=>x.reviewed).length,unclassified=items.filter(x=>x.requirement==='unclassified').length,lessons=assessedLessons(records),latest=lessons[0],assessment=latest&&readLessonAssessment(latest.body.tutorPrivate?.lessonAssessment),comparisons=lessonComparisons(records),checkpoints=records.filter(r=>r.visibility==='teacher'&&r.kind==='test'&&readCheckpoint(r.body.tutorPrivate?.checkpoint)).sort((a,b)=>b.date.localeCompare(a.date)),teacherScores=assessment?.teaching.filter(t=>t.score!=null)||[];
 return <section className="teacher-insights" aria-label={`${name}’s learning dashboard`}>
  <header className="insight-header"><div><p className="teacher-eyebrow">LEARNING DASHBOARD · PRIVATE TO RORY</p><h2>Practice, learning and your teaching</h2><p>Each result names the task, date and evidence behind it.</p></div><button className="teacher-quiet-button" onClick={()=>void refresh()}>Refresh dashboard</button></header>
  <div className="insight-metrics">
   <Metric label="Required homework received" value={required.length?`${Math.round(received/required.length*100)}%`:'Not set'} detail={required.length?`${received} of ${required.length} available required tasks received or marked complete; ${reviewed} reviewed.`:`${unclassified} tasks need a required / optional choice.`}/>
   <Metric label="Saved activity days" value={String(activity.activeDays)} detail={`${days?`Last ${days} days`:'All saved history'} · conversations, answers and quiz attempts.`}/>
   <Metric label="Latest assessed lesson" value={latest?readableDate(latest.date).replace(/^\w+, /,''):'Not assessed'} detail={assessment?`${assessment.checks.filter(c=>c.score!==null).length} scored task checks · Draft; Rory review pending.`:'A prepared deck does not count as a completed lesson.'}/>
   <Metric label="Retained learning" value={comparisons.some(x=>x.change!==null)?`${comparisons.filter(x=>x.change!==null).length} comparable checks`:'Next check needed'} detail="A later independent task must match the earlier objective and conditions."/>
   <Metric label="Your teaching" value={teacherScores.length?`${teacherScores.length} checks scored`:'Not scored yet'} detail="Private scores out of 4 for specific teaching actions, supported by lesson evidence."/>
  </div>
  <div className="insight-grid">
   <article className="insight-card"><h3>Homework follow-through</h3><p>Choose which available tasks are required. Optional recap practice is excluded. This percentage measures receipt, not accuracy.</p>{unclassified>0&&<p className="mt-2 font-semibold">{unclassified} unclassified tasks are excluded from the percentage.</p>}
    <p className="mt-3"><strong>{required.filter(x=>x.overdue).length}</strong> required tasks overdue · <strong>{required.filter(x=>x.revision).length}</strong> need revision</p>
    <div className="insight-task-list">{items.map(x=><div key={x.id}><strong>{x.title}</strong><span>{x.revision?'Revision requested':x.reviewed?'Reviewed / marked complete':x.received?'Received · awaiting review':'Not fully received'}{x.overdue?' · overdue':''}</span><small>{x.due?`Due ${readableDate(x.due)}`:'No deadline set'}</small><label>Requirement<select className={box} value={settings.requirements[x.id]||'unclassified'} onChange={e=>setSettings(s=>({...s,requirements:{...s.requirements,[x.id]:e.target.value as Requirement}}))}><option value="unclassified">Choose required or optional</option><option value="required">Required</option><option value="optional">Optional practice</option></select></label></div>)}</div>{!items.length&&<p className="mt-3">No available tasks in the current unit or school year.</p>}<p className="mt-3 text-xs">Linked chat + writing count as one set, received when both are saved. Opening a task is not completion. The choices here organise your dashboard; student instructions still define the work.</p><button className="re-button re-secondary mt-3" onClick={onReview}>Review answers and uploads</button>
   </article>
   <article className="insight-card"><div className="flex flex-wrap items-center justify-between gap-3"><h3>How much is the app being used?</h3><label>Window<select className={box} value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={0}>All saved history</option></select></label></div>
    <div className="insight-activity"><Metric label="Saved conversations" value={String(activity.conversations)} detail="Student conversations"/><Metric label="Tasks sent" value={String(activity.answers)} detail="Latest receipt per task"/><Metric label="Quiz attempts" value={String(activity.quizzes)} detail="Saved quiz rows"/></div>
    <p>Latest saved activity in this window: <strong>{activity.last?readableDate(activity.last):'None found'}</strong></p><p className="mt-2">These are saved actions across devices. This count covers conversations, submitted tasks and quiz rows. Uploads and lesson-recap replies are kept in their own work records. App visits, total time online, abandoned conversations and unsent drafts are not currently measured.</p>
    <details className="mt-3"><summary className="cursor-pointer font-semibold">Days with saved work</summary><p className="mt-2">{activity.dates.map(readableDate).join(' · ')||'No saved activity in this window.'}</p></details>
   </article>
   <article className="insight-card"><h3>What changed since earlier lessons?</h3><p>Task support scores: 1 = unfinished after help; 2 = substantial help; 3 = small hint; 4 = own words. Accuracy and support are assessed separately.</p>{comparisons.map(x=><div className="insight-check" key={x.task}><strong>{x.task}</strong><span>{x.score===null?'Not assessed':`${x.score} / 4`}</span><p>{x.change===null?'No comparable earlier independent check yet.':`${x.change>0?'+':''}${x.change} support points since ${readableDate(x.before!)} · same recorded protocol.`}</p></div>)}{!comparisons.length&&<p className="mt-3">No scored lesson checks yet.</p>}{assessment&&<p className="mt-3"><strong>Later retention:</strong> {assessment.retainedProgress}</p>}<button className="re-button re-secondary mt-3" onClick={onNotes}>Open all feedback and lesson notes</button>
   </article>
   <article className="insight-card"><h3>Progress against school expectations</h3><p>{unit?.title||'Current unit not confirmed'}</p><p className="mt-2">Judge the learner against the actual school task and their earlier comparable work. Age alone cannot set an English score.</p><label className="mt-3 block">Confirmed age, class / year, school objectives and success criteria<textarea className={box} rows={4} maxLength={1500} value={settings.schoolContext} onChange={e=>setSettings(s=>({...s,schoolContext:e.target.value}))} placeholder="Record confirmed facts and the expected independent task. Leave unknown details unconfirmed."/></label><p className="mt-2 text-xs">No age or grade benchmark is assigned automatically.</p>
   </article>
  </div>
  <div className="my-4 flex flex-wrap items-center gap-3"><button className="re-button" disabled={busy||JSON.stringify(settings)===JSON.stringify(savedSettings)} onClick={()=>void saveSettings()}>{busy?'Saving…':'Save requirements & school context'}</button>{JSON.stringify(settings)!==JSON.stringify(savedSettings)&&<p className="text-sm">Unsaved dashboard choices</p>}{message&&<p role="status" className="text-sm">{message}</p>}</div>
  <article className="insight-card mb-4"><h3>Unit words in saved conversations</h3><p>Exact words and phrases found in the learner’s captions, checked against the current unit list. Captions can contain recognition mistakes; appearance does not establish correct use, independence or mastery. Variants and synonyms are not automatically counted.</p>{records.filter(r=>r.kind==='speaking'&&r.author==='Student'&&r.visibility==='shared'&&r.body.transcript).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(r=>{const coverage=vocabularyCoverage(r.body.transcript!,unit?.voiceVocabulary||[]);return <div className="insight-check" key={r.id}><strong>{r.title} · {readableDate(r.date)}</strong>{coverage?<><p><strong>{coverage.found.length} of {coverage.total} current unit targets found</strong> · {coverage.learnerWords} caption words</p><p>Found: {coverage.found.join(', ')||'None'}</p><details><summary className="cursor-pointer">Targets not found in these captions</summary><p>{coverage.missing.join(', ')||'All targets appeared.'}</p></details></>:<p>Coverage unavailable: no recognised learner captions or verified unit word list.</p>}</div>;})}<p className="mt-3 text-xs">This applies today’s word list to the displayed conversation, even if its topic differed. Speech rate, pronunciation, talk-time share and response latency need separately verified audio timing and are not scored from caption timestamps.</p></article>
  <article className="insight-card"><h3>Rory’s checkpoints</h3><p>Suggested rhythm: a short retrieval / exit check each lesson; a 15–20-minute checkpoint after a unit or about every 3–4 lessons. Test taught vocabulary, grammar and relevant skills with fresh tasks. Repeat an equivalent independent task later to check retention.</p><CheckpointForm code={code} onSaved={refresh}/>
   {checkpoints.map((r,i)=>{const c=readCheckpoint(r.body.tutorPrivate?.checkpoint)!,result=checkpointResult(c);let change:number|null=null;for(const previous of checkpoints.slice(i+1)){if(previous.date>=r.date)continue;change=checkpointChange(readCheckpoint(previous.body.tutorPrivate?.checkpoint)!,c);if(change!==null)break;}return <details className="insight-checkpoint" key={r.id}><summary><strong>{r.title} · {readableDate(r.date)}</strong><span>{result?`${result.earned} / ${result.possible} · ${result.percent}%`:'Not fully assessed'}</span></summary><p className="mt-3">{c.objective} · {c.support}</p><p className="mt-2">{change===null?'No comparable earlier checkpoint result.':`${change>0?'+':''}${change} percentage points on a comparable independent checkpoint.`}</p>{c.criteria.map(x=><p className="mt-2" key={x.skill}><strong>{x.skill}: {x.earned??'—'} / {x.possible}</strong> · {x.evidence||'Not checked'}</p>)}<p className="mt-3"><strong>What went well:</strong> {c.strength}</p><p><strong>Practise next:</strong> {c.target}</p><p><strong>Next check:</strong> {c.nextCheck}</p><CheckpointShare code={code} record={r} checkpoint={c} onSaved={refresh}/></details>;})}
  </article>
  {latest&&<article className="insight-card mt-4"><h3>Latest lesson and your teaching · {readableDate(latest.date)}</h3><LessonAssessmentPanel key={`${latest.id}-${latest.created}`} record={latest} records={records} code={code} onSaved={()=>void refresh()}/></article>}
  <article className="insight-card mt-4"><h3>Your teaching over time</h3><p>Compare the same teaching action across observed lessons. Each score stays beside its evidence; there is no combined teaching percentage.</p>{lessons.slice(0,5).map(r=>{const a=readLessonAssessment(r.body.tutorPrivate?.lessonAssessment)!;return <details className="insight-checkpoint" key={r.id}><summary>{readableDate(r.date)} · {a.teaching.filter(t=>t.score!=null).length} scored checks</summary>{a.teaching.map(t=><p className="mt-2" key={t.title}><strong>{t.title}: {t.score==null?'Not scored':`${t.score} / 4`}</strong> · {t.observation}</p>)}</details>;})}{!lessons.length&&<p className="mt-3">No observed lesson teaching checks yet.</p>}</article>
  <article className="insight-card mt-4"><h3>What {name} and their parents see</h3><p>Required homework instructions, receipt / revision status, Rory-approved strengths, one or two next targets, and dated results with their marks and scope. practice advice stays labelled. Share a lesson summary only after reviewing it; your teaching scores, school-context notes and full draft analyses stay private.</p></article>
 </section>;
}
function CheckpointForm({code,onSaved}:{code:string;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[date,setDate]=useState(viennaDay()),[objective,setObjective]=useState(''),[protocol,setProtocol]=useState(''),[support,setSupport]=useState('Independent first attempt'),[rows,setRows]=useState([{skill:'Vocabulary in new sentences',earned:'',possible:'5',evidence:''},{skill:'Grammar in context',earned:'',possible:'5',evidence:''}]),[strength,setStrength]=useState(''),[target,setTarget]=useState(''),[next,setNext]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[id,setId]=useState('');
 const checkpoint:Checkpoint={version:1,objective,protocol,support,criteria:rows.map(x=>({skill:x.skill,earned:x.earned.trim()===''?null:Number(x.earned),possible:Number(x.possible),evidence:x.evidence})),strength,target,nextCheck:next};
 const valid=title.trim()&&objective.trim()&&next.trim()&&date<=viennaDay()&&/^20\d\d-\d\d-\d\d$/.test(date)&&rows.every(x=>x.skill.trim())&&readCheckpoint(checkpoint);
 async function save(e:React.FormEvent){e.preventDefault();if(!valid||busy)return;setBusy(true);setMessage('');const recordId=id||crypto.randomUUID();setId(recordId);try{const r=await saveLearning(code,{id:recordId,date,kind:'test',title:title.trim(),visibility:'teacher',body:{evidenceType:'Rory’s checkpoint · private',tutorPrivate:{checkpoint}}});if(!r.ok)throw Error(r.error||'Could not save checkpoint.');setTitle('');setObjective('');setProtocol('');setStrength('');setTarget('');setNext('');setRows([{skill:'Vocabulary in new sentences',earned:'',possible:'5',evidence:''},{skill:'Grammar in context',earned:'',possible:'5',evidence:''}]);setId('');setOpen(false);await onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Could not save checkpoint.');}finally{setBusy(false);}}
 return <div className="mt-4"><button className="re-button re-secondary" onClick={()=>setOpen(!open)}>{open?'Close checkpoint form':'+ Record my own checkpoint'}</button>{open&&<form className="mt-4 space-y-3" onSubmit={e=>void save(e)}><p>Record an actual completed test. Leave an untested score blank. Explain the marking criteria and the learner’s response; a percent appears only when every criterion has been marked.</p><div className="grid gap-3 sm:grid-cols-2"><label>Test title<input className={box} maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Actual assessment date<input className={box} type="date" max={viennaDay()} value={date} onChange={e=>setDate(e.target.value)} required/></label></div><label className="block">Taught objective / unit and pages<input className={box} maxLength={400} value={objective} onChange={e=>setObjective(e.target.value)} required/></label><label className="block">Comparison protocol · objective, task difficulty, length, time and help<input className={box} maxLength={600} value={protocol} onChange={e=>setProtocol(e.target.value)} placeholder="Reuse only for genuinely equivalent first attempts; blank means no comparison."/></label><label className="block">Help given<select className={box} value={support} onChange={e=>setSupport(e.target.value)}>{['Independent first attempt','Small hints','Model or substantial help','Reading supplied words'].map(x=><option key={x}>{x}</option>)}</select></label>
 {rows.map((x,i)=><fieldset key={i} className="rounded-xl border border-black/15 p-3 dark:border-white/20"><legend>Criterion {i+1}</legend><label>Skill / marking criterion<input className={box} maxLength={250} value={x.skill} onChange={e=>setRows(s=>s.map((v,j)=>j===i?{...v,skill:e.target.value}:v))}/></label><div className="grid grid-cols-2 gap-3"><label>Marks earned · blank if not assessed<input className={box} type="number" min={0} max={Number(x.possible)} step="0.5" value={x.earned} onChange={e=>setRows(s=>s.map((v,j)=>j===i?{...v,earned:e.target.value}:v))}/></label><label>Maximum marks<input className={box} type="number" min={0.5} max={1000} step="0.5" value={x.possible} onChange={e=>setRows(s=>s.map((v,j)=>j===i?{...v,possible:e.target.value}:v))}/></label></div><label>Marking evidence / success criteria<textarea className={box} rows={2} maxLength={800} value={x.evidence} onChange={e=>setRows(s=>s.map((v,j)=>j===i?{...v,evidence:e.target.value}:v))} placeholder="What earns each mark, what they produced and any help."/></label>{rows.length>1&&<button type="button" className="mt-2 underline" onClick={()=>setRows(s=>s.filter((_,j)=>j!==i))}>Remove criterion</button>}</fieldset>)}<button type="button" className="underline" disabled={rows.length>=8} onClick={()=>setRows(s=>[...s,{skill:'',earned:'',possible:'5',evidence:''}])}>Add reading, listening, speaking, writing or another criterion</button>
 {([['What went well',strength,setStrength],['Practise next',target,setTarget],['Next independent retention check',next,setNext]] as const).map(([label,value,setter])=><label className="block" key={label}>{label}<textarea className={box} rows={2} maxLength={600} value={value} onChange={e=>setter(e.target.value)}/></label>)}<button className="re-button" disabled={!valid||busy}>{busy?'Saving…':'Save private checkpoint'}</button>{message&&<p role="status">{message}</p>}</form>}</div>;
}
function CheckpointShare({code,record,checkpoint:c,onSaved}:{code:string;record:LearningRecord;checkpoint:Checkpoint;onSaved:()=>Promise<void>}){
 const result=checkpointResult(c),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[open,setOpen]=useState(false),[summary,setSummary]=useState(`${record.title}: ${result?`${result.earned} / ${result.possible} (${result.percent}%)`:'Not fully assessed'}. ${c.objective}. Help: ${c.support}. This result describes this checkpoint.`),[strength,setStrength]=useState(c.strength),[target,setTarget]=useState(c.target),[next,setNext]=useState(c.nextCheck);
 async function share(){setBusy(true);setMessage('');try{const r=await saveLearning(code,{id:`${record.id}-summary`,date:record.date,kind:'test',title:`Checkpoint feedback · ${record.title}`.slice(0,150),visibility:'shared',body:{evidenceType:'Checkpoint · reviewed by Rory',source:`checkpoint-summary:${record.id}`,summary,strengths:strength.trim()?[strength]:[],targets:target.trim()?[target]:[],nextStep:next}});if(!r.ok)throw Error(r.error||'Could not share feedback.');setMessage('Rory-reviewed checkpoint feedback saved.');await onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Could not share feedback.');}finally{setBusy(false);}}
 return <div className="mt-3"><button className="re-button re-secondary" onClick={()=>setOpen(!open)}>Preview student & parent feedback</button>{open&&<div className="mt-3 space-y-3"><p>Check the result and wording before approval. Only these four fields are shared.</p>{([['Summary and scoped result',summary,setSummary],['What went well',strength,setStrength],['Practise next',target,setTarget],['Try this',next,setNext]] as const).map(([label,value,setter])=><label className="block" key={label}>{label}<textarea className={box} rows={2} maxLength={1500} value={value} onChange={e=>setter(e.target.value)}/></label>)}<button className="re-button" disabled={busy||!summary.trim()||!next.trim()} onClick={()=>void share()}>{busy?'Sharing…':'Approve and share checkpoint feedback'}</button></div>}{message&&<p role="status" className="mt-2">{message}</p>}</div>;
}
