import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const load=(f,deps={})=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>deps[n],Date,Set,Map});return exports;};const s=load('src/lib/skill-progress.ts'),m=load('src/lib/learning-goals.ts',{'./skill-progress':s});
const goal={id:'past-story',domain:'grammar',title:'Use past verbs in an original account',criterion:'One mark per correct past verb in five new clauses',source:'Verified textbook Unit1 and agreed marking guide',threshold:80};
const plan={version:1,planId:'fixed-plan-1',title:'Unit1 goals v1',age:'',classYear:'',schoolType:'',confirmed:false,expectedLevel:'',goals:[goal,{...goal,id:'reading',domain:'reading',title:'Reading'}]};
const record=(id,date,patch={})=>({id,date,created:date,kind:'test',title:'Observed independent work',visibility:'teacher',author:'Rory',body:{tutorPrivate:{skillCheck:{version:1,sourceKind:'lesson',unitId:'unit1',unitTitle:'Family life',protocol:'Five new clauses, no model',help:'independent',stage:'baseline',results:[{domain:'grammar',goalId:goal.id,goalPlanId:plan.planId,criterion:goal.criterion,earned:4,possible:5,evidence:'four correct original clauses',evidenceType:'written'}],vocabularySource:'',words:[],nextCheck:'new contexts',...patch}}}});
test('goal coverage counts a fixed real plan and keeps untested goals explicit',()=>{assert.ok(m.readGoalPlan(plan));const p=m.goalProgress(plan,[record('a','2026-10-01')]);assert.equal(p.percent,50);assert.equal(p.demonstrated,1);assert.equal(p.total,2);assert.equal(p.assessed,1);assert.equal(p.retained,0);});
test('supported work, mismatched criteria and other plan versions cannot prove a goal',()=>{assert.equal(m.goalProgress(plan,[record('a','2026-10-01',{help:'hints'})]).demonstrated,0);const r=record('a','2026-10-01');r.body.tutorPrivate.skillCheck.results[0].goalPlanId='other';assert.equal(m.goalProgress(plan,[r]).assessed,0);r.body.tutorPrivate.skillCheck.results[0].goalPlanId=plan.planId;r.body.tutorPrivate.skillCheck.results[0].criterion='Different marking scheme';assert.equal(m.goalProgress(plan,[r]).demonstrated,0);});
test('retention requires a later equivalent independent success, including transfer to another topic',()=>{const a=record('a','2026-10-01'),b=record('b','2026-10-10',{stage:'retention',unitId:'unit2'});assert.equal(m.goalProgress(plan,[a,b]).retained,1);assert.equal(m.goalProgress(plan,[a,{...b,date:a.date}]).retained,0);assert.equal(m.goalProgress(plan,[a,record('c','2026-10-10',{stage:'retention',protocol:'changed task'})]).retained,0);});
test('school expectation cannot be confirmed without actual age, class, course and target; zero or duplicate goal thresholds are invalid',()=>{assert.equal(m.readGoalPlan({...plan,confirmed:true}),null);assert.ok(m.readGoalPlan({...plan,age:'15',classYear:'5th AHS',schoolType:'AHS English first language',expectedLevel:'Confirmed course descriptors',confirmed:true}));for(const patch of [{goals:[{...goal,threshold:0}]},{goals:[goal,goal]},{planId:''}])assert.equal(m.readGoalPlan({...plan,...patch}),null);});

test('an average cannot hide a B2 writing criterion below its published minimum descriptor',()=>{
 const g={...goal,domain:'writing',threshold:60},p={...plan,goals:[g]},r=record('b2','2026-10-03');r.body.tutorPrivate.skillCheck.results=[{...r.body.tutorPrivate.skillCheck.results[0],domain:'writing',rubric:'austrian-b2-writing',subscores:{task:8,organisation:8,range:8,accuracy:5},earned:29,possible:40}];assert.equal(m.goalProgress(p,[r]).demonstrated,0);r.body.tutorPrivate.skillCheck.results[0].subscores.accuracy=6;r.body.tutorPrivate.skillCheck.results[0].earned=30;assert.equal(m.goalProgress(p,[r]).demonstrated,1);
});
