import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const load=(f,deps={})=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>deps[n],Date,Set,Map});return exports;};
const skills=load('src/lib/skill-progress.ts'),goals=load('src/lib/learning-goals.ts',{'./skill-progress':skills}),common=load('src/lib/evidence-common.ts');
const m=load('src/lib/progress-visuals.ts',{'./skill-progress':skills,'./learning-goals':goals,'./evidence-common':common,'./progress-evidence':{observationHistory:rs=>rs.filter(r=>r.body.tutorPrivate?.progressObservation).map(record=>({record,observation:record.body.tutorPrivate.progressObservation}))}});
const check={version:1,sourceKind:'lesson',unitId:'named-audio-sample',unitTitle:'A specific audio excerpt',protocol:'Fixed fresh narrative, 60s',help:'independent',stage:'baseline',results:[{domain:'pronunciation',criterion:'Audio intelligibility rubric, not accent accuracy',earned:3,possible:4,evidence:'Actual learner audio clip',evidenceType:'audio'}],vocabularySource:'',words:[],nextCheck:'Repeat under the same conditions'};
const record=(id,date,body)=>({id,date,created:date+'T10:00:00Z',kind:'test',title:'Audio sample draft',author:'AI draft',visibility:'teacher',body});
test('qualitative coverage never becomes attainment marks; missing skills stay null',()=>{const r=record('qual','2026-04-10',{tutorPrivate:{progressObservation:{observations:[{domain:'writing'},{domain:'grammar'}]}}}),p=m.visualProgress([r]);assert.equal(p.reviewed,2);assert.equal(p.marked,0);assert.ok(p.areas.every(a=>a.percent===null));assert.equal(p.goals,null);});
test('named audio task marks appear independently of school goals and require actual audio evidence',()=>{const r=record('audio','2026-10-03',{tutorPrivate:{skillCheck:check}}),p=m.visualProgress([r]);assert.equal(p.marked,1);assert.equal(p.areas.find(a=>a.domain==='pronunciation').percent,75);assert.equal(p.goals,null);assert.equal(m.visualProgress([record('caption','2026-10-03',{tutorPrivate:{skillCheck:{...check,results:[{...check.results[0],evidenceType:'transcript'}]}}})]).marked,0);});
test('unlike historic audio clips cannot show a change; repeated saves do not double count',()=>{const a=record('a','2026-09-19',{tutorPrivate:{skillCheck:check}}),b=record('b','2026-10-03',{tutorPrivate:{skillCheck:{...check,unitId:'other-audio-sample',results:[{...check.results[0],earned:4}]}}});const p=m.visualProgress([a,b,b]);assert.equal(p.marked,1);assert.equal(p.areas.find(a=>a.domain==='pronunciation').change,null);assert.equal(p.areas.find(a=>a.domain==='pronunciation').percent,100);});
