import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/skill-progress.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,Set,Map});const m=exports;
const check={version:1,unitId:'unit1',unitTitle:'Family life · pp 10–25',protocol:'10 new words in fresh sentences, 5 minutes, same rubric, no hints',help:'independent',stage:'baseline',results:[{domain:'vocabulary',criterion:'One mark per correct word in a fresh context',earned:6,possible:10,evidence:'6 correct independent answers in the saved work',evidenceType:'written'}],vocabularySource:'Book p 12 list v1',words:[{word:'family',recall:true,use:true,retained:null,previousDate:'',evidence:'Defined it correctly and made an original sentence'},{word:'relative',recall:false,use:null,retained:null,previousDate:'',evidence:'Could not recall the meaning'}],nextCheck:'Repeat with different contexts next lesson'};
const record=(id,date,c=check)=>({id,date,created:date,kind:'test',title:'A real marked test',author:'Rory',visibility:'teacher',body:{tutorPrivate:{skillCheck:c}}});
test('attainment uses marks; missing scores remain absent and zero is a real result',()=>{assert.ok(m.readSkillCheck(check,'2026-10-03'));assert.equal(m.skillPercent(check.results[0]),60);assert.equal(m.skillPercent({...check.results[0],earned:null}),null);assert.equal(m.skillPercent({...check.results[0],earned:0}),0);for(const patch of [{earned:11},{earned:-1},{earned:NaN},{evidence:''}])assert.equal(m.readSkillCheck({...check,results:[{...check.results[0],...patch}]},'2026-10-03'),null);});
test('skill progress uses eight domains and dated latest results; unrelated units and help do not produce improvement',()=>{const later={...check,results:[{...check.results[0],earned:8}]};const e=m.skillEntries([record('a','2026-10-01'),record('b','2026-10-03',later)],true),d=m.domainProgress(e,'unit1');assert.equal(d.length,8);assert.equal(d[0].change,20);assert.equal(d[1].result,null);assert.equal(m.skillChange(check,{...later,unitId:'unit2'},'vocabulary'),null);for(const patch of [{help:'hints'},{protocol:''},{protocol:'another task'},{results:[{...later.results[0],criterion:'Different rubric'}]},{results:[{...later.results[0],possible:20}]}])assert.equal(m.skillChange(check,{...later,...patch},'vocabulary'),null);const same=m.domainProgress(m.skillEntries([record('a','2026-10-03'),record('b','2026-10-03',later)],true),'unit1');assert.equal(same[0].change,null);});
test('caption-only pronunciation or fluency percentages are rejected; audio evidence is required',()=>{for(const domain of ['pronunciation','fluency']){const r={...check.results[0],domain};assert.equal(m.readSkillCheck({...check,results:[{...r,evidenceType:'transcript'}]},'2026-10-03'),null);assert.ok(m.readSkillCheck({...check,results:[{...r,evidenceType:'audio'}]},'2026-10-03'));}});
test('word coverage has a fixed denominator, exposes untested counts and does not invent retained mastery',()=>{const p=m.wordProgress(check);assert.equal(p[0].percent,50);assert.equal(p[0].checked,2);assert.equal(p[1].checked,1);assert.equal(p[2].checked,0);for(const previousDate of ['','2026-10-03','2026-10-04','2026-02-31'])assert.equal(m.readSkillCheck({...check,words:[{...check.words[0],retained:true,previousDate}]},'2026-10-03'),null);assert.ok(m.readSkillCheck({...check,words:[{...check.words[0],retained:true,previousDate:'2026-09-20'}]},'2026-10-03'));assert.equal(m.readSkillCheck({...check,help:'hints'},'2026-10-03'),null);assert.equal(m.readSkillCheck({...check,words:[{...check.words[0],recall:false,retained:true,previousDate:'2026-09-20'}]},'2026-10-03'),null);});
test('vocabulary trends require a complete equivalent fixed list; adding words or changing list scope gives no false decline',()=>{const complete={...check,words:check.words.map(w=>({...w,use:false,retained:null}))},later={...complete,words:complete.words.map(w=>({...w,recall:true,use:true}))};assert.equal(m.wordChange(complete,later,'recall'),50);assert.equal(m.wordChange(check,later,'use'),null);assert.equal(m.wordChange(complete,{...later,words:[...later.words,{...later.words[0],word:'sibling'}]},'recall'),null);assert.equal(m.wordChange(complete,{...later,vocabularySource:'Full book unit list v2'},'recall'),null);});
test('publication is an explicit whitelist; students only receive approved separate snapshots and teachers do not double count',()=>{const snapshot=m.skillSnapshot(check);assert.ok(m.readSkillSnapshot(snapshot,'2026-10-03'));assert.doesNotMatch(JSON.stringify(snapshot),/6 correct independent answers|original sentence|tutorPrivate|evidence"/);const privateRecord=record('a','2026-10-03'),publicRecord={...privateRecord,id:'a-progress-summary',visibility:'shared',body:{skillSnapshot:snapshot,source:'skill-progress-summary:a'}};assert.equal(m.skillEntries([privateRecord],false).length,0);assert.equal(m.skillEntries([privateRecord,publicRecord],true).length,1);assert.equal(m.skillEntries([privateRecord,publicRecord],false).length,1);assert.equal(m.skillEntries([{...publicRecord,author:'Student'}],false).length,0);});
test('malformed and prototype skill keys are rejected safely',()=>{for(const patch of [{results:[null]},{words:[null]},{results:[{...check.results[0],domain:'toString'}]},{words:[...check.words,check.words[0]]},{unitId:''},{unitId:123},{unitTitle:null},{results:[...check.results,check.results[0]]}])assert.equal(m.readSkillCheck({...check,...patch},'2026-10-03'),null);});

test('the family progress panel renders percentages, history and untested areas without private marking evidence',async()=>{
 const React=await import('react'),runtime=await import('react/jsx-runtime'),{renderToStaticMarkup}=await import('react-dom/server');const componentExports={};
 const clarity={readableDate:d=>d},teacherMetrics={viennaDay:()=> '2026-10-05'};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/components/SkillProgressPanel.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:componentExports,require:n=>({'react':React,'react/jsx-runtime':null,'@/lib/skill-progress':m,'@/lib/learning-goals':{activeGoalPlan:()=>null},'@/lib/learning':{},'@/lib/teacher-metrics':teacherMetrics,'@/lib/clarity':clarity}[n])||jsxRuntime(n),console});
 function jsxRuntime(n){if(n==='react/jsx-runtime')return runtime;if(n==='./ProgressVisualSummary')return {default:()=>null};throw Error(n);}
 // The runtime is loaded before rendering; no network or actual learner data is used.
 const publicRecord={...record('a','2026-10-03'),visibility:'shared',body:{source:'skill-progress-summary:a',skillSnapshot:m.skillSnapshot(check)}};
 const html=renderToStaticMarkup(React.createElement(componentExports.default,{records:[publicRecord]}));assert.match(html,/60%/);assert.match(html,/6 \/ 10 marks/);assert.match(html,/Grammar/);assert.match(html,/Not assessed/);assert.match(html,/50%/);assert.match(html,/still untested/);assert.doesNotMatch(html,/6 correct independent answers|Defined it correctly|Assess skills/);
 const empty=renderToStaticMarkup(React.createElement(componentExports.default,{records:[record('private','2026-10-03')]}));assert.match(empty,/when Rory shares them/);assert.doesNotMatch(empty,/0 of 8|Not assessed|6 correct independent answers/);
});

test('teacher progress drill-down keeps private assessments visible while family views filter them',async()=>{
 const React=await import('react'),runtime=await import('react/jsx-runtime'),{renderToStaticMarkup}=await import('react-dom/server');let calls=0;const componentExports={};
 const hooks={...React,useEffect:()=>{},useState:initial=>[++calls===1?[record('private','2026-10-03')]:calls===3?false:typeof initial==='function'?initial():initial,()=>{}]};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/components/SkillProgressPanel.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:componentExports,require:n=>({'react':hooks,'react/jsx-runtime':runtime,'@/lib/skill-progress':m,'@/lib/learning-goals':{activeGoalPlan:()=>null},'@/lib/learning':{},'@/lib/teacher-metrics':{viennaDay:()=> '2026-10-05'},'@/lib/clarity':{readableDate:d=>d},'./ProgressVisualSummary':{default:()=>React.createElement('p',null,'Private progress chart')}}[n]),console});
 const html=renderToStaticMarkup(React.createElement(componentExports.SharedSkillProgress,{code:'synthetic',teacher:true}));assert.match(html,/Private teacher view/);assert.match(html,/Private progress chart/);assert.match(html,/60%/);assert.match(html,/6 correct independent answers/);assert.match(html,/Preview progress for student/);assert.doesNotMatch(html,/0 of 8 areas assessed/);
});

test('official B2 writing keeps four separate bands, correct totals and no invented overall-level conversion',()=>{
 const subscores={task:6,organisation:7,range:8,accuracy:5},writing={...check.results[0],domain:'writing',rubric:'austrian-b2-writing',subscores,earned:26,possible:40};assert.ok(m.readSkillCheck({...check,results:[writing]},'2026-10-03'));assert.equal(m.skillPercent(writing),65);assert.equal(m.readSkillCheck({...check,results:[{...writing,earned:30}]},'2026-10-03'),null);assert.equal(m.readSkillCheck({...check,results:[{...writing,subscores:{...subscores,accuracy:11}}]},'2026-10-03'),null);assert.equal(m.b2WritingTotal({...subscores,accuracy:null}),null);assert.equal(m.readSkillCheck({...check,results:[{...writing,domain:'grammar'}]},'2026-10-03'),null);
});
