import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/teaching-files.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,URL});
const pack={kind:'lesson',visibility:'teacher',body:{tutorPrivate:{plan:'Teaching files:\nPowerPoint: https://drive.google.com/file/d/abc_123/view\nNotes: https://drive.google.com/file/d/def-456/view'}}};
test('teaching files require a private lesson and explicit pack marker',()=>{assert.equal(exports.teachingFiles(pack).length,2);assert.equal(exports.teachingFiles({...pack,visibility:'shared'}).length,0);assert.equal(exports.teachingFiles({...pack,kind:'homework'}).length,0);assert.equal(exports.teachingFiles({...pack,body:{tutorPrivate:{plan:'Ordinary reflection'}}}).length,0);});
test('teaching-file links reject scripts, insecure URLs and lookalike Drive hosts',()=>{const plan='Teaching files:\nBad: javascript:alert(1)\nBad: http://drive.google.com/file/d/abc/view\nBad: https://drive.google.com.evil.test/file/d/abc/view\nBad: https://drive.google.com/file/d/abc/view?extra=1';assert.equal(exports.teachingFiles({...pack,body:{tutorPrivate:{plan}}}).length,0);});

test('uploaded PowerPoint and PDF links retain official Drive parameters',()=>{const plan='Teaching files:\nPowerPoint: https://docs.google.com/presentation/d/abc123/edit?usp=drivesdk&ouid=123&rtpof=true&sd=true\nNotes: https://drive.google.com/file/d/def456/view?usp=drivesdk';assert.equal(exports.teachingFiles({...pack,body:{tutorPrivate:{plan}}}).length,2);});

test('preparation packs are distinguishable from lesson reflections even if links need repair',()=>{assert.equal(exports.isTeachingPack(pack),true);assert.equal(exports.isTeachingPack({...pack,body:{tutorPrivate:{plan:'Teaching files:\nBroken link'}}}),true);assert.equal(exports.isTeachingPack({...pack,body:{tutorPrivate:{plan:'Use a shorter opening next time'}}}),false);});
