import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const load=(file,deps={})=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>deps[n]||(()=>{throw Error(n)})(),Date,Intl,Map,Set});return exports;};
const a=load('src/lib/lesson-assessment.ts'),caption=load('src/lib/conversation-transcript.ts'),v=load('src/lib/vocabulary-coverage.ts',{'./conversation-transcript':caption});
const m=load('src/lib/teacher-metrics.ts',{'./clarity':load('src/lib/clarity.ts'),'./remote':{isCurrentAssignment:a=>/^2026-(09|10|11|12)/.test(a.date)},'./speaking-homework':load('src/lib/speaking-homework.ts'),'./guided-speaking':load('src/lib/guided-speaking.ts'),'./lesson-assessment':a,'./teaching-files':load('src/lib/teaching-files.ts')});
const config={version:1,requirements:{},schoolContext:''};const submission=(task,status='submitted',submitted='2026-10-03T14:00:00Z')=>({id:task,task,unit:'unit1',submitted,status,feedback:'',answers:{}});
const checkpoint={version:1,objective:'Unit 1 verbs',protocol:'Five new sentences; 5 minutes; same marking scheme; no hints',support:'Independent first attempt',criteria:[{skill:'Correct past verbs',earned:3,possible:5,evidence:'3 of 5 new sentences used a correct verb; 1 mark each.'}],strength:'Used two verbs',target:'Irregular forms',nextCheck:'5 new sentences next lesson'};
test('checkpoint percentages need complete real marks; zero is valid, unassessed is not zero',()=>{assert.equal(m.checkpointResult(checkpoint).percent,60);assert.equal(m.checkpointResult({...checkpoint,criteria:[{...checkpoint.criteria[0],earned:null}]}),null);assert.equal(m.checkpointResult({...checkpoint,criteria:[{...checkpoint.criteria[0],earned:0}]}).percent,0);assert.equal(m.readCheckpoint({...checkpoint,criteria:[{...checkpoint.criteria[0],earned:6}]}),null);assert.equal(m.readCheckpoint({...checkpoint,criteria:[{...checkpoint.criteria[0],evidence:''}]}),null);});
test('progress comparisons reject changed support, objective, marking scheme or missing protocol',()=>{const after={...checkpoint,criteria:[{...checkpoint.criteria[0],earned:4}]};assert.equal(m.checkpointChange(checkpoint,after),20);for(const changed of [{support:'Small hints'},{protocol:''},{objective:'Different objective'},{criteria:[{...after.criteria[0],possible:10}]}])assert.equal(m.checkpointChange(checkpoint,{...after,...changed}),null);});
test('homework counts latest received and reviewed work separately, respects required choices and future releases',()=>{const unit={id:'unit1',homework:[{week:1,title:'First',due:'2026-10-01'},{week:2,title:'Second',due:''},{week:3,title:'Future',availableFrom:'2026-12-01',due:''}]};const sent=[submission('hw:1','reviewed','2026-10-01'),submission('hw:1','revision-needed','2026-10-03')];const r=m.homeworkMetrics('a',unit,[],sent,[],{...config,requirements:{'unit:unit1:hw:1':'required'}},'2026-10-05');assert.equal(r.length,2);assert.equal(r[0].received,true);assert.equal(r[0].reviewed,false);assert.equal(r[0].revision,true);assert.equal(r[0].overdue,false);assert.equal(r[1].requirement,'unclassified');});
test('combined Ferdi assignment is replaced by two linked chat and writing sets with exact receipt conditions',()=>{const code='ferdi-7h3k',unit={id:'english-in-context5-unit01-2026',homework:[1,2].map(week=>({week,title:'Set '+week,due:''}))},assignments=[{id:'combo',date:'2026-09-23',title:'Combined',details:'Chat 1: Tell a story. Chat 2: Compare',due:'',status:'open'}],sent=[{...submission('hw:1'),unit:unit.id}],chat={kind:'speaking',author:'Student',title:'Family life · Chat 1: story',body:{}};assert.equal(m.homeworkMetrics(code,unit,assignments,sent,[],config,'2026-10-05')[0].received,false);const r=m.homeworkMetrics(code,unit,assignments,sent,[chat],config,'2026-10-05');assert.equal(r.length,2);assert.equal(r[0].received,true);assert.equal(r[1].received,false);});
test('saved activity excludes teacher preparation, future actions and duplicate revisions; audio analyses do not shift the action date',()=>{const records=[{kind:'lesson',author:'Rory',visibility:'teacher',date:'2026-10-03',body:{}},{kind:'speaking',author:'Student',visibility:'shared',date:'2026-09-01',created:'2026-10-05',body:{submittedAt:'2026-09-01T14:00:00Z'}},{kind:'speaking',author:'Student',visibility:'shared',date:'2026-10-03',body:{}}],sent=[submission('a','submitted','2026-10-01'),submission('a','submitted','2026-10-03'),submission('future','submitted','2026-12-01')];const r=m.activityMetrics(records,sent,{quizzes:{headers:['Date','Score'],rows:[['2026-10-02',2],['',2]]}},7,'2026-10-05');assert.equal(r.conversations,1);assert.equal(r.answers,1);assert.equal(r.quizzes,1);assert.equal(r.activeDays,2);assert.equal(r.last,'2026-10-03');assert.equal(m.eventDay('2026-10-03T23:30:00Z'),'2026-10-04');assert.equal(m.eventDay('2026-02-31'),null);});
test('vocabulary is exact learner-caption coverage, not partner language or partial-word/lemma mastery',()=>{const c=v.vocabularyCoverage('[1.0s] AI partner: family friendly day out\n[2.0s] You: My family had a day out.\n[3.0s] AI partner: grandfather\n[4.0s] You: I visited grandfathers.', ['family','day out','friendly','grandfather','family']);assert.equal(c.total,4);assert.deepEqual([...c.found],['family','day out']);assert.equal(v.vocabularyCoverage('unclear speaker text',['family']),null);assert.equal(v.vocabularyCoverage('[0.0s] AI partner: family',['family']),null);});
test('private teaching ratings retain backward compatibility and reject unobserved zero ratings',()=>{const assessment={version:1,method:'Support',limits:'Transcript',attempts:[],checks:[],areas:[],withinLesson:'Practice',retainedProgress:'Unknown',teaching:[{title:'Instructions',observation:'Learner followed the task',time:'01:00'}]};assert.ok(a.readLessonAssessment(assessment));assert.ok(a.readLessonAssessment({...assessment,teaching:[{...assessment.teaching[0],score:3}]}));assert.equal(a.readLessonAssessment({...assessment,teaching:[{...assessment.teaching[0],score:0}]}),null);});
test('new private checkpoint, school context and teaching metrics are excluded from student, parent and preview reads',()=>{
 const body={summary:'Safe summary',tutorPrivate:{checkpoint,skillCheck:{evidence:'PRIVATE SKILL MARKING EVIDENCE'},goalPlan:{age:'PRIVATE AGE',criterion:'PRIVATE SCHOOL EXPECTATION'},schoolContext:'PRIVATE SCHOOL CONTEXT',dashboardSettings:config,lessonAssessment:{teaching:[{score:3,observation:'PRIVATE TEACHING'}]}}};
 const rows=[['private-test','2026-10-05','2026-10-03','test','Checkpoint','teacher',JSON.stringify(body),'Rory',''],['shared-summary','2026-10-05','2026-10-03','test','Feedback','shared',JSON.stringify(body),'Rory','']];
 const sheet={getDataRange:()=>({getValues:()=>[['header'],...rows]})},ctx={Date,JSON,Object,Array,String,Number,isNaN,studentByAnyCode_:()=>({code:'a',parentCode:'parent-a'}),studentSheet_:()=>({getSheetByName:name=>name==='Learning reviews'?sheet:null}),reviewHeld_:()=>false};vm.createContext(ctx);vm.runInContext(fs.readFileSync('apps-script/progress-sync/Learning.gs','utf8'),ctx);
 for(const [role,code,preview] of [['student','a',false],['parent','parent-a',false],['teacher','a',true]]){const result=ctx.learningService_({action:'learningRecords',code,preview},{role,code});assert.equal(result.ok,true);assert.equal(result.records.length,1);assert.equal(result.records[0].body.tutorPrivate,undefined);assert.doesNotMatch(JSON.stringify(result),/PRIVATE|checkpoint|skillCheck|goalPlan|dashboardSettings|lessonAssessment/);}
 const teacher=ctx.learningService_({action:'learningRecords',code:'a'},{role:'teacher'});assert.equal(teacher.records.length,2);assert.equal(teacher.records[0].body.tutorPrivate.checkpoint.criteria[0].earned,3);
});
