"use client";
import {readLessonSnapshot,supportLabels,type Support} from '@/lib/lesson-assessment';
import {readLessonPractice} from '@/lib/lesson-practice';
import type {LearningRecord} from '@/lib/learning';
import {readableDate} from '@/lib/clarity';

export function SupportChart({counts,scope}:{counts:Record<Support,number>;scope:string}){
 const colours:Record<Support,string>={independent:'#31856c',prompted:'#4863b6',modelled:'#ad7925','read-aloud':'#80719f'},total=Object.values(counts).reduce((x,y)=>x+y,0);let angle=0;const segments=(Object.keys(counts) as Support[]).map(k=>{const start=angle;angle+=total?counts[k]/total*360:0;return `${colours[k]} ${start}deg ${angle}deg`;}).join(',');
 return <div className="mt-3 flex flex-wrap items-center gap-5"><div className="relative h-32 w-32 shrink-0 rounded-full" role="img" aria-label={`${total} selected attempts: ${(Object.keys(counts) as Support[]).map(k=>`${counts[k]} ${supportLabels[k]}`).join(', ')}`} style={{background:total?`conic-gradient(${segments})`:'#ddd'}}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-surface dark:bg-navy-raised"><strong className="text-2xl">{total}</strong><span className="text-xs">checked attempts</span></div></div><div><ul className="space-y-1">{(Object.keys(counts) as Support[]).map(k=><li key={k}><span className="mr-2 inline-block h-3 w-3 rounded-full" style={{background:colours[k]}}/>{supportLabels[k]}: {counts[k]}</li>)}</ul><p className="mt-2 max-w-md text-xs">{scope}</p></div></div>;
}
export function ApprovedLessonSummary({value}:{value:unknown}){
 const s=readLessonSnapshot(value);if(!s)return null;
 return <section className="mt-4 rounded-xl border border-indigo-200 p-4 text-sm dark:border-indigo-800"><h4 className="font-bold">Lesson progress · checked by Rory</h4><p className="mt-2">{s.summary}</p><h5 className="mt-3 font-semibold">What went well</h5><ul className="ml-5 list-disc">{s.strengths.map(x=><li key={x}>{x}</li>)}</ul><h5 className="mt-3 font-semibold">Practise next</h5><ul className="ml-5 list-disc">{s.targets.map(x=><li key={x}>{x}</li>)}</ul><p className="mt-3"><strong>Try this:</strong> {s.nextStep}</p>
  {(s.counts||s.checks.length>0)&&<details className="mt-4"><summary className="cursor-pointer font-semibold">How much help was needed?</summary><p className="mt-2 text-xs">{s.scope}</p>{s.counts&&<SupportChart counts={s.counts} scope="Selected attempts only, not a percentage of English ability or the whole lesson."/>}{s.checks.map(c=><p className="mt-2" key={c.task}>{c.task}: <strong>{c.score===null?'Not checked':`${c.score} / 4`}</strong></p>)}<p className="mt-2 text-xs">1: still needs help to finish · 2: finished after an example or lots of help · 3: finished with a small hint · 4: finished using their own words. A finished answer can still have language mistakes. These scores apply to these tasks only. Progress means needing less help on a similar new task; one result cannot show lasting improvement.</p></details>}
  <p className="mt-3 text-xs">Reviewed by Rory · {readableDate(s.reviewedAt.slice(0,10))}</p>
 </section>;
}
export default function LessonProgressSummary({records,parent=false}:{records:LearningRecord[];parent?:boolean}){
 const approved=records.filter(r=>r.visibility==='shared'&&!r.reviewPending&&readLessonSnapshot(r.body.lessonSnapshot)).sort((a,b)=>b.date.localeCompare(a.date));
 const practice=records.filter(r=>r.visibility==='shared'&&!r.reviewPending&&readLessonPractice(r.body.lessonPractice)?.status==='ready').sort((a,b)=>b.date.localeCompare(a.date))[0];
 const latest=approved[0],p=practice&&readLessonPractice(practice.body.lessonPractice);
 return <section className="re-card" aria-label="Lesson progress overview"><h3 className="font-bold">{parent?'Your child’s lesson progress':'Your lesson progress'}</h3><p className="mt-2 text-sm">{latest?`Latest checked lesson: ${readableDate(latest.date)}.`:'Rory has not yet approved a detailed recorded lesson assessment for sharing.'}</p>{latest&&<a className="mt-2 inline-block underline text-sm" href={`#review-${latest.id}`}>Read Rory’s lesson feedback</a>}{p&&(!latest||practice.date>latest.date)&&<div className="mt-3 text-sm"><strong>Latest lesson recap · {readableDate(p.lessonDate)}</strong><p className="mt-1">{p.recap}</p><p className="mt-1">Optional practice: about {p.speakingMinutes+p.writingMinutes} minutes. This recap is AI prepared practice; the detailed assessment awaits Rory’s review.</p><a className="mt-2 inline-block underline" href={`#review-${practice.id}`}>Open recap and practice</a></div>}<p className="mt-3 text-xs">{parent?'Encourage one short attempt and notice what your child can do with less help.':'Try a fresh example. The next lesson will check what you can do with less help.'} We compare the learner with their own earlier work, using similar tasks.</p></section>;
}
