"use client";
import {SupportChart} from '@/components/LessonProgressSummary';
import {useState} from 'react';
import {readLessonAssessment,supportCounts,supportLabels,matchedChange} from '@/lib/lesson-assessment';
import {saveLearning,publishLessonSnapshot,type LearningRecord} from '@/lib/learning';
import {readableDate} from '@/lib/clarity';
export default function LessonAssessmentPanel({record,records,code,onSaved}:{record:LearningRecord;records:LearningRecord[];code:string;onSaved:()=>void}){
 const a=readLessonAssessment(record.body.tutorPrivate?.lessonAssessment),[editing,setEditing]=useState(false),[scores,setScores]=useState<(number|null)[]>([]),[teachingScores,setTeachingScores]=useState<(number|null)[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[sharing,setSharing]=useState(false),[shareText,setShareText]=useState({summary:'',strengths:'',targets:'',nextStep:''}),[includeMetrics,setIncludeMetrics]=useState(false);
 if(!a)return null;const counts=supportCounts(a);
 const previous=records.filter(r=>r.id!==record.id&&r.date<record.date).sort((x,y)=>y.date.localeCompare(x.date));
 async function save(){if(!a||busy)return;setBusy(true);setMessage('');const updated={...a,checks:a.checks.map((c,i)=>({...c,score:scores[i]})),teaching:a.teaching.map((t,i)=>({...t,score:teachingScores[i]}))};const r=await saveLearning(code,{...record,body:{...record.body,tutorPrivate:{...record.body.tutorPrivate,lessonAssessment:updated}}});setBusy(false);if(r.ok){setEditing(false);setMessage('Draft scores saved privately. The review is still pending.');onSaved();}else setMessage(r.error||'Could not save draft scores.');}
 async function publish(){if(busy)return;setBusy(true);setMessage('');const result=await publishLessonSnapshot(code,record.id,{summary:shareText.summary,strengths:shareText.strengths.split('\n').map(x=>x.trim()).filter(Boolean),targets:shareText.targets.split('\n').map(x=>x.trim()).filter(Boolean),nextStep:shareText.nextStep},includeMetrics);setBusy(false);if(result.ok){setSharing(false);setMessage(result.record?.reviewPending?'Reviewed summary saved. It will appear after the usual feedback release time.':'Rory’s reviewed summary is now available to this student and their parents. The detailed draft stays private.');onSaved();}else setMessage(result.error||'Could not publish the lesson summary.');}
 return <section className="mt-4 rounded-xl border border-indigo-200 p-4 text-sm dark:border-indigo-800" aria-label="Detailed recorded lesson assessment">
  <h4 className="text-lg font-bold">Detailed lesson assessment · draft · Rory review pending</h4><p className="mt-2">{a.method.replace(/a model/g,'an example sentence (model)')}</p><p className="mt-2 text-xs">{a.limits}</p>
  <h5 className="mt-4 font-bold">How much help was used?</h5><SupportChart counts={counts} scope="This chart counts the selected attempts below. It is not a percentage of English ability or of the whole lesson."/>
  <h5 className="mt-5 font-bold">Task scores · doing it with less help</h5><p className="mt-1 text-xs">1: still needs help to finish · 2: finished after an example or lots of help · 3: finished with a small hint · 4: finished using their own words. A dash means not checked. Language can still need corrections at any support score. These are provisional classroom scores, not exam grades.</p>
  <div className="mt-3 space-y-4">{a.checks.map((c,i)=>{let comparison:string='No matching earlier scored check yet.';for(const r of previous){const before=readLessonAssessment(r.body.tutorPrivate?.lessonAssessment);if(!before)continue;const change=matchedChange(before,a,c.key);if(change!==null){comparison=`Comparable check on ${readableDate(r.date)}: ${change>0?'+':''}${change} point${Math.abs(change)===1?'':'s'}.`;break;}}return <div key={c.key} className="rounded-xl bg-black/5 p-3 dark:bg-white/5"><div className="flex items-center justify-between gap-3"><strong>{c.task}</strong><span className="whitespace-nowrap font-bold">{c.score??'—'} / 4</span></div><div className="mt-2 flex gap-1" aria-hidden="true">{[1,2,3,4].map(n=><span key={n} className={`h-2 flex-1 rounded ${c.score!==null&&n<=c.score?'bg-indigo-500':'bg-black/10 dark:bg-white/15'}`}/>)}</div><p className="mt-2">{c.evidence}</p><p className="mt-2 text-xs">{comparison}</p><p className="mt-2"><strong>Next check:</strong> {c.nextCheck}</p>{editing&&<label className="mt-2 block">Rory’s draft score <select className="ml-2 rounded border bg-transparent p-1" value={scores[i]??''} onChange={e=>setScores(x=>x.map((v,j)=>j===i?e.target.value?Number(e.target.value):null:v))}><option value="">Not checked</option>{[1,2,3,4].map(n=><option key={n} value={n}>{n}</option>)}</select></label>}</div>;})}</div>
  <p className="mt-4"><strong>Change within this lesson:</strong> {a.withinLesson}</p><p className="mt-2"><strong>Progress remembered later:</strong> {a.retainedProgress}</p>
  <details className="mt-4"><summary className="cursor-pointer font-bold">Speaking areas and timestamped evidence</summary><div className="mt-3 space-y-3">{a.areas.map(x=><p key={x.title}><strong>{x.title}{!x.assessed?' · not measured':''}:</strong> {x.observation}</p>)}<h5 className="font-bold">Selected attempts behind the chart</h5>{a.attempts.map(x=><p key={x.id}><strong>{x.time} · {x.task} · {supportLabels[x.support]}</strong><br/>{x.evidence}<span className="mt-1 block text-xs">Evidence confidence: {x.confidence}</span></p>)}</div></details>
  <details className="mt-4"><summary className="cursor-pointer font-bold">Rory’s teaching · specific checks</summary><p className="mt-3">Private classroom rubric for each teaching action: 1 = needs a substantial change; 2 = partly effective; 3 = effective with a specific adjustment; 4 = effective in the observed task. Use the observation and learner response as evidence. Leave unseen actions blank; these are not a validated overall teacher grade.</p><div className="mt-3 space-y-3">{a.teaching.map(x=><p key={x.title}><strong>{x.title} · {x.time}</strong><span className="ml-2 font-bold">{x.score==null?"Not scored":`${x.score} / 4`}</span><br/>{x.observation}{editing&&<label className="mt-2 block">Your private teaching score <select className="ml-2 rounded border bg-transparent p-1" value={teachingScores[a.teaching.indexOf(x)]??''} onChange={e=>setTeachingScores(values=>values.map((v,i)=>i===a.teaching.indexOf(x)?e.target.value?Number(e.target.value):null:v))}><option value="">Not observed</option>{[1,2,3,4].map(n=><option key={n} value={n}>{n} / 4</option>)}</select></label>}</p>)}</div></details>
  <details className="mt-4 text-xs"><summary className="cursor-pointer font-semibold">Research and scoring method</summary><p className="mt-2">The speaking areas draw on <a className="underline" href="https://www.cambridgeenglish.org/pt/Images/168143-cambridge-english-preliminary-for-schools-teachers-handbook.pdf" target="_blank" rel="noopener noreferrer">Cambridge speaking criteria</a>, <a className="underline" href="https://www.coe.int/en/web/common-european-framework-reference-languages/phonological-competence" target="_blank" rel="noopener noreferrer">Council of Europe intelligibility guidance</a> and <a className="underline" href="https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/feedback" target="_blank" rel="noopener noreferrer">EEF feedback guidance</a>. The four support steps are our classroom tracking method, not Cambridge’s exam scale. Compare the same objective, difficulty and first-attempt conditions before claiming progress. Repeating an example shows practice with help; using the language alone later still needs checking.</p></details>
  <details className="mt-4 rounded-xl border border-black/10 p-3 dark:border-white/15" open={sharing} onToggle={e=>setSharing(e.currentTarget.open)}><summary className="cursor-pointer font-bold" onClick={()=>{if(!sharing){const b=record.body;setShareText({summary:b.plainReview?.summary||b.summary||'',strengths:(b.plainReview?.strengths||b.strengths||[]).slice(0,3).join('\n'),targets:(b.plainReview?.targets||b.targets||[]).slice(0,3).join('\n'),nextStep:b.plainReview?.nextStep||b.nextStep||''});}}}>Preview a summary for student and parents</summary><div className="mt-3 space-y-3"><p>Check and edit these words before approving. Only this summary and any selected task metrics are shared. The recording, transcript and teaching notes remain private.</p>{(['summary','strengths','targets','nextStep'] as const).map(k=><label className="block" key={k}>{k==='summary'?'What happened':k==='strengths'?'What went well · up to three lines':k==='targets'?'Practise next · up to three lines':'Next small step'}<textarea className="mt-1 w-full rounded-lg border bg-transparent p-2" rows={3} maxLength={k==='summary'?1200:k==='nextStep'?800:1202} value={shareText[k]} onChange={e=>setShareText({...shareText,[k]:e.target.value})}/></label>)}<label className="flex gap-2"><input type="checkbox" checked={includeMetrics} onChange={e=>setIncludeMetrics(e.target.checked)}/>I have checked the selected attempts and task scores; include them with the summary.</label><button className="re-button" disabled={busy||!shareText.summary.trim()} onClick={()=>void publish()}>Approve and share this summary</button><p className="text-xs">This publishes a separate reviewed record for this learner. It does not approve the entire draft.</p></div></details>
  <div className="mt-4 flex gap-2">{!editing?<button className="re-button re-secondary" onClick={()=>{setScores(a.checks.map(c=>c.score));setTeachingScores(a.teaching.map(t=>t.score??null));setEditing(true);}}>Edit draft scores</button>:<><button className="re-button" disabled={busy} onClick={()=>void save()}>Save private draft</button><button className="re-button re-secondary" onClick={()=>setEditing(false)}>Cancel</button></>}</div>{message&&<p role="status" className="mt-2">{message}</p>}
 </section>;
}
