'use client';
import {useState} from 'react';
import ProgressVisualSummary from './ProgressVisualSummary';
import {evidenceKinds,observationHistory,progressEvidence,type ProgressEvidence,type EvidenceKind} from '@/lib/progress-evidence';
import {skillDomains} from '@/lib/skill-progress';
import {readableDate} from '@/lib/clarity';
import type {LearningRecord,LearningReply} from '@/lib/learning';
import type {LearnerDocument} from '@/lib/documents';
import type {Progress,Submission} from '@/lib/remote';
const labels={'needs-review':'Assessment needed',draft:'Evidence review drafted',marked:'Marked check linked','receipt-only':'Completion only','original-needed':'Original / marking guide needed'};
export default function ProgressPortfolioPanel({records,documents,submissions,replies,progress,error,onAssess}:{records:LearningRecord[];documents:LearnerDocument[];submissions:Submission[];replies:LearningReply[];progress:Progress|null;error:string;onAssess:(source:ProgressEvidence)=>void}){
 const [filter,setFilter]=useState<EvidenceKind|''>(''),catalog=progressEvidence({records,documents,submissions,replies,progress}),history=observationHistory(records),items=catalog.items.filter(e=>!filter||e.kind===filter);
 return <section className="insight-card mb-5" aria-label="Progress evidence across all work"><p className="teacher-eyebrow">ONE RECORD ACROSS ALL OUR WORK · PRIVATE TO RORY</p><h2 className="text-xl font-bold">Where we started, where we are now</h2><p className="mt-2">Earlier recordings and original writing form a historical starting picture. Recent work updates it. The school benchmark remains provisional until the current class and course are confirmed.</p><ProgressVisualSummary records={records}/>
 {history.length>0?<div className="skill-progress-grid mt-4">{Object.entries(skillDomains).map(([domain,label])=>{const examples=history.flatMap(h=>h.observation.observations.filter(o=>o.domain===domain).map(o=>({...h,detail:o}))),first=examples[0],last=examples.at(-1);return <article className="skill-progress-tile" key={domain}><h3>{label}</h3>{first?<><p className="mt-3"><strong>Earliest evidence · {readableDate(first.record.date)}{first.observation.dateBasis==='available-by'?' · available by this date':first.observation.dateBasis==='unknown'?' · work date unverified':''}</strong></p><p className="mt-2">{first.detail.finding}</p>{last!==first&&<><p className="mt-3"><strong>Latest evidence · {readableDate(last!.record.date)}{last!.observation.dateBasis==='available-by'?' · available by this date':last!.observation.dateBasis==='unknown'?' · work date unverified':''}</strong></p><p className="mt-2">{last!.detail.finding}</p></>}<details className="mt-3"><summary className="cursor-pointer">Evidence, help &amp; limits</summary>{examples.map((e,i)=><div key={`${e.record.id}-${i}`} className="mt-3"><p><strong>{readableDate(e.record.date)}</strong> · {e.detail.help} · {e.detail.confidence} · Draft; Rory review pending</p><p>{e.detail.evidence}</p><p className="mt-2 text-xs">{e.observation.method}<br/>{e.observation.limits}</p></div>)}</details></>:<p className="mt-3">No verified historical comparison yet. A focused check can fill this gap.</p>}</article>;})}</div>:<p className="mt-3 font-semibold">Historical evidence is being gathered. A new test is only needed for gaps the existing work cannot answer.</p>}
 {history.length>0&&<details className="mt-4"><summary className="cursor-pointer font-bold">Review history, teaching notes &amp; next checks</summary>{history.map(h=><article className="mt-4 border-t border-black/10 pt-3 dark:border-white/10" key={h.record.id}><h3>{h.record.title}</h3><p className="mt-2">{h.observation.method}</p><p className="mt-2">{h.observation.limits}</p><p className="mt-2"><strong>Next check:</strong> {h.observation.nextCheck}</p>{h.record.body.tutorPrivate?.worked&&<p className="mt-2"><strong>Teaching that helped:</strong> {h.record.body.tutorPrivate.worked}</p>}{h.record.body.tutorPrivate?.improve&&<p className="mt-2"><strong>Teaching to adjust:</strong> {h.record.body.tutorPrivate.improve}</p>}</article>)}</details>}
 <div className="flex flex-wrap items-end justify-between gap-3 mt-5"><div><h3>Evidence feeding progress</h3><p>{catalog.items.length} saved sources · {catalog.items.filter(e=>e.status==='marked').length} with linked marked checks · {catalog.items.filter(e=>e.status==='draft').length} draft reviews</p></div><label>Show<select className="mt-1 block rounded-lg border border-black/15 bg-transparent p-2 dark:border-white/20" value={filter} onChange={e=>setFilter(e.target.value as EvidenceKind|'')}><option value="">All evidence</option>{Object.entries(evidenceKinds).map(([id,label])=><option value={id} key={id}>{label} · {catalog.items.filter(e=>e.kind===id).length}</option>)}</select></label></div>
 <p className="mt-3 text-sm">Saved app conversations, uploads, answers, replies, revisions, quiz rows and school results enter this list when the dashboard refreshes. Lesson recordings enter after a private recording review. Every source is available for assessment; scores need a marking guide and observed evidence.</p>
 {error&&<p role="alert" className="mt-3">{error} <strong>The evidence list may be incomplete.</strong></p>}
 <div className="mt-3">{items.map(e=><details className="insight-checkpoint" key={e.ref}><summary><span><strong>{e.title}</strong><small className="block mt-1">{evidenceKinds[e.kind]} · {e.date?readableDate(e.date):'Date not verified'}{e.dateBasis==='available-by'?' · upload date; performance date unconfirmed':''}</small></span><span>{labels[e.status]}</span></summary><p className="mt-3">{e.summary}</p><p className="mt-2 text-xs">Source: {e.ref}{e.aliases?.length?` · linked records: ${e.aliases.join(', ')}`:''}</p>{e.original&&<details className="mt-3"><summary className="cursor-pointer">Original learner evidence</summary><p className="whitespace-pre-wrap break-words mt-2">{e.original}</p></details>}<button className="re-button re-secondary mt-3" onClick={()=>onAssess(e)}>Assess this work</button></details>)}</div>
 {!items.length&&<p className="mt-3">No saved evidence in this category yet.</p>}
 <p className="mt-3 text-xs">{catalog.excluded} software test records excluded · {catalog.planned} preparation / practice-resource entries kept separate. Repeated saves with the same ID count once. Completion and participation do not establish learning; qualitative differences do not become a percentage change.</p>
 </section>;
}
