import type {LearningRecord} from '@/lib/learning';
import {visualProgress} from '@/lib/progress-visuals';
import {skillDomains} from '@/lib/skill-progress';
import {readableDate} from '@/lib/clarity';
import ProgressRing from './ProgressRing';
const help={independent:'Independent',hints:'With hints',model:'With a model',unknown:'Help / preparation unknown'};
export default function ProgressVisualSummary({records}:{records:LearningRecord[]}){
 const p=visualProgress(records);
 return <div className="progress-visual-summary mt-4"><div className="progress-overview-grid">
  <article className="progress-overview-tile"><h3>Learning goals achieved</h3><ProgressRing value={p.goals?.assessed?p.goals.percent:null} label="Goals achieved" detail={p.goals?`${p.goals.demonstrated} of ${p.goals.total} fixed goals demonstrated independently · ${p.goals.total-p.goals.assessed} unassessed`:'Set the fixed learning goals first.'}/><p>{p.plan?.confirmed?'Against the confirmed course goals.':'Proposed tutoring goals; school benchmark awaiting confirmation.'}</p></article>
  <article className="progress-overview-tile"><h3>Evidence available</h3><div className="progress-coverage" role="img" aria-label={`${p.reviewed} of ${p.total} skill areas have reviewed examples; ${p.marked} have marked tasks`}><strong>{p.reviewed}<span> / {p.total}</span></strong><div className="progress-coverage-dots" aria-hidden="true">{p.areas.map(a=><span key={a.domain} className={a.result?'marked':a.observed?'reviewed':'missing'}/>)}</div></div><p>{p.marked} areas with task marks · {p.total-p.reviewed} still need evidence</p><p>Reviewed examples help us choose what to assess next.</p></article>
  <article className="progress-overview-tile"><h3>Age &amp; school benchmark</h3><strong className="progress-benchmark-status">{p.plan?.confirmed?p.plan.expectedLevel:'Awaiting confirmation'}</strong><p>{p.plan?.classYear||'Class / year needed'} · {p.plan?.schoolType||'Course needed'}</p><p>{p.plan?.age?`Age: ${p.plan.age}. `:''}{p.plan?.confirmed?'Expected course standard; current level must be demonstrated.':'Current age, school year and course must be confirmed before judging whether the student meets the expected standard.'}</p></article>
 </div><div className="progress-skill-chart mt-4"><div className="flex flex-wrap justify-between gap-2"><h3>Latest marked task in each skill</h3><span className="text-sm">{p.marked} of {p.total} assessed</span></div><p className="mt-1 text-sm">Bars show marks on the named task or audio rubric. Each skill keeps its own date, difficulty and help; an audio band is not a percentage of sounds pronounced correctly.</p><div className="progress-skill-bars mt-3">{p.areas.map(a=><article key={a.domain}><div className="progress-skill-bar-title"><h4>{skillDomains[a.domain]}</h4><strong>{a.percent===null?'Not assessed':`${a.percent}%`}</strong></div><div className={`progress-bar-track${a.percent===null?' unassessed':''}`} role="img" aria-label={`${skillDomains[a.domain]}: ${a.percent===null?'not assessed':`${a.percent}% of task marks`}`}><span style={{width:`${a.percent??0}%`}}/></div>{a.result&&a.latest?<p>{a.result.earned}/{a.result.possible} · {readableDate(a.latest.record.date)} · {help[a.latest.check.help]}<br/>{a.latest.check.unitTitle}{a.latest.record.author==='AI draft'&&<> · Draft assessment; Rory review pending</>}{a.change!==null&&<> · {a.change>0?'+':''}{a.change} percentage points on comparable checks</>}</p>:<p>{a.observed?'Reviewed examples available; task marking needed.':['pronunciation','fluency'].includes(a.domain)?'Actual audio review needed.':'Evidence and a marked check needed.'}</p>}</article>)}</div></div></div>;
}
