"use client";
import {useEffect,useRef,useState} from "react";
import {calendarAction} from "@/lib/calendar-client";
import {fileBase64} from "@/lib/documents";
import {prepareDocumentFiles,validateDocumentSelection} from "@/lib/document-photos";
import {lessonDate,viennaDate,type SchoolTest} from "@/lib/lesson-calendar";
type Student={code:string;name:string};
type Draft={id:string;mutationId:string;code:string;date:string;title:string;scope:string;expectedSequence?:number;existing:SchoolTest["files"];removeFiles:number[]};
type Run=(code:string,action:string,body:Record<string,unknown>,success:string)=>Promise<boolean>;
export default function SchoolTestCalendar({tests,code,selected,day,teacher,parent,preview,students,busy,error,loaded,run}:{tests:SchoolTest[];code:string;selected:string;day:string;teacher:boolean;parent:boolean;preview:boolean;students:Student[];busy:boolean;error:string;loaded:boolean;run:Run}){
  const [draft,setDraft]=useState<Draft|null>(null),[past,setPast]=useState(false),[cancel,setCancel]=useState<{test:SchoolTest;mutationId:string}|null>(null);
  const canEdit=!preview&&!parent;
  const list=tests.filter(t=>(past||t.date>=viennaDate())&&(!day||t.date===day)).sort((a,b)=>a.date.localeCompare(b.date)||a.title.localeCompare(b.title));
  function edit(t?:SchoolTest){setDraft({id:t?.id||crypto.randomUUID(),mutationId:crypto.randomUUID(),code:t?.studentCode||selected,date:t?.date||day||viennaDate(),title:t?.title||"English test",scope:t?.scope||"",expectedSequence:t?.sequence,existing:t?.files||[],removeFiles:[]});}
  return <section className="cal-panel cal-tests" aria-label="School tests"><div className="cal-section-heading"><div><p className="re-eyebrow">PLAN YOUR TEST PREPARATION</p><h2>School tests</h2></div>{canEdit&&<button className="cal-primary" disabled={busy||!selected} onClick={()=>edit()}>+ Add test</button>}</div><p className="cal-muted">Save the date and what to study. Write the scope, attach photos of the school’s instructions, or use both.</p><label className="cal-check"><input type="checkbox" checked={past} onChange={e=>setPast(e.target.checked)}/>Include past tests</label>{loaded&&!list.length&&<p className="cal-muted">{day?"No school tests on this date.":"No upcoming school tests added yet."}</p>}
    <div className="cal-test-list">{list.map(t=><article key={`${t.studentCode}-${t.id}`} className={`cal-lesson cal-test ${t.status==="cancelled"?"is-cancelled":""}`}><div className="cal-lesson-top"><p>{lessonDate(t.date)}</p><span className={`cal-badge ${t.status==="cancelled"?"cancelled":"test"}`}>{t.status==="cancelled"?"Cancelled":"School test"}</span></div><h3>{t.title}</h3>{teacher&&<p className="cal-muted">{t.studentName}</p>}<h4>What to study</h4>{t.scope&&<p className="cal-test-scope">{t.scope}</p>}{!!t.files.length&&<TestPhotos test={t} code={teacher?t.studentCode:code} teacher={teacher}/>}<div className="cal-lesson-actions">{canEdit&&<><button className="cal-button" disabled={busy} onClick={()=>edit(t)}>{t.status==="cancelled"?"Restore or edit test":"Edit test"}</button>{t.status!=="cancelled"&&<button className="cal-text-button" disabled={busy} onClick={()=>setCancel({test:t,mutationId:crypto.randomUUID()})}>Cancel test</button>}</>}</div></article>)}</div>
    {draft&&<TestEditor key={draft.id} draft={draft} setDraft={setDraft} students={students} teacher={teacher} busy={busy} error={error} onClose={()=>setDraft(null)} run={run}/>}
    {cancel&&<TestDialog title="Cancel this test?" busy={busy} onClose={()=>setCancel(null)}><p>{cancel.test.title} · {lessonDate(cancel.test.date)}. Its scope and photos will be kept.</p>{error&&<p role="alert" className="cal-alert">{error}</p>}<div className="cal-dialog-actions"><button className="cal-button" disabled={busy} onClick={()=>setCancel(null)}>Keep test</button><button className="cal-primary" disabled={busy} onClick={async()=>{if(await run(teacher?cancel.test.studentCode:code,teacher?"teacherCalendarTestCancel":"calendarTestCancel",{id:cancel.test.id,mutationId:cancel.mutationId,expectedSequence:cancel.test.sequence},"School test cancelled."))setCancel(null);}}>Cancel test</button></div></TestDialog>}
  </section>;
}
function TestDialog({title,busy,onClose,children}:{title:string;busy:boolean;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return <dialog ref={ref} className="cal-dialog" aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="cal-dialog-heading"><h2>{title}</h2><button className="cal-icon-button" type="button" disabled={busy} aria-label="Close test form" onClick={onClose}>×</button></div>{children}</dialog>;}
function TestEditor({draft,setDraft,students,teacher,busy,error,onClose,run}:{draft:Draft;setDraft:(draft:Draft)=>void;students:Student[];teacher:boolean;busy:boolean;error:string;onClose:()=>void;run:Run}){
  const [photos,setPhotos]=useState<File[]>([]),[localError,setLocalError]=useState(""),[preparing,setPreparing]=useState(false),[previews,setPreviews]=useState<string[]>([]);
  const pending=busy||preparing;
  const patch=(change:Partial<Draft>)=>setDraft({...draft,...change,mutationId:crypto.randomUUID()});
  useEffect(()=>{const urls=photos.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[photos]);
  function choose(files:File[]){const problem=validateDocumentSelection(files);if(problem){setLocalError(problem);return;}if(files.some(f=>!f.type.startsWith("image/")&&!/\.hei[cf]$/i.test(f.name))){setLocalError("Choose photos of the test scope.");return;}setLocalError("");setPhotos(files);patch({});}
  async function save(){setLocalError("");if(!draft.scope.trim()&&!photos.length&&draft.existing.length===draft.removeFiles.length){setLocalError("Write the test scope or add a photo of it.");return;}setPreparing(true);try{const prepared=photos.length?await prepareDocumentFiles(photos):[];const files=await Promise.all(prepared.map(async f=>({name:f.name,type:f.type,data:await fileBase64(f)})));const {code,existing,...body}=draft;void existing;if(await run(code,teacher?"teacherCalendarTestSave":"calendarTestSave",{...body,files},"School test saved."))onClose();}catch(e){setLocalError(e instanceof Error?e.message:"Could not prepare these photos. Choose them again.");}finally{setPreparing(false);}}
  return <TestDialog title={draft.expectedSequence===undefined?"Add school test":"Edit school test"} busy={pending} onClose={onClose}><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={pending}><div className="cal-form-grid">{teacher&&<label className="cal-field"><span>Student</span><select disabled={draft.expectedSequence!==undefined} value={draft.code} onChange={e=>patch({code:e.target.value})}>{students.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label>}<label className="cal-field"><span>Test date</span><input required type="date" value={draft.date} onChange={e=>patch({date:e.target.value})}/></label></div><label className="cal-field"><span>Test title</span><input required maxLength={120} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label className="cal-field"><span>Test scope · what to study</span><textarea rows={5} maxLength={4000} placeholder="Units, pages, vocabulary, grammar and writing tasks…" value={draft.scope} onChange={e=>patch({scope:e.target.value})}/></label><p className="cal-muted">Write the scope or add a photo. You can save both.</p>{draft.existing.map(f=><label key={f.index} className="cal-check"><input type="checkbox" checked={!draft.removeFiles.includes(f.index)} onChange={e=>patch({removeFiles:e.target.checked?draft.removeFiles.filter(i=>i!==f.index):[...draft.removeFiles,f.index]})}/>Keep {f.name}</label>)}<label className="cal-field"><span>Upload scope photos</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif" onChange={e=>choose(Array.from(e.target.files||[]))}/></label><label className="cal-field"><span>Take a scope photo</span><input type="file" accept="image/*" capture="environment" onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length)choose([...photos,...files]);}}/></label><p className="cal-muted">Up to six photos. Large photos are prepared for upload; the originals on your device stay unchanged.</p>{!!photos.length&&<><div className="cal-photo-grid">{previews.map((url,i)=><figure key={url}><img src={url} alt={`Selected scope photo ${i+1}`}/><figcaption>{photos[i]?.name}</figcaption></figure>)}</div><button type="button" className="cal-text-button" onClick={()=>{setPhotos([]);patch({});}}>Clear selected photos</button></>}</fieldset>{(localError||error)&&<p role="alert" className="cal-alert">{localError||error}</p>}<div className="cal-dialog-actions"><button type="button" className="cal-button" disabled={pending} onClick={onClose}>Close</button><button type="submit" className="cal-primary" disabled={pending}>{pending?"Saving…":"Save test"}</button></div></form></TestDialog>;
}
function TestPhotos({test,code,teacher}:{test:SchoolTest;code:string;teacher:boolean}){
  const [urls,setUrls]=useState<Record<number,string>>({}),[error,setError]=useState(""),[loading,setLoading]=useState<number|null>(null),generation=useRef(0);
  const allocated=useRef<string[]>([]);
  useEffect(()=>{generation.current++;setUrls({});setError("");setLoading(null);const old=allocated.current;allocated.current=[];old.forEach(u=>URL.revokeObjectURL(u));return()=>{generation.current++;allocated.current.forEach(u=>URL.revokeObjectURL(u));allocated.current=[];};},[code,test.id,test.sequence]);
  async function open(index:number){const current=generation.current;setLoading(index);setError("");try{const r=await calendarAction(code,teacher?"teacherCalendarTestFile":"calendarTestFile",{id:test.id,index,expectedSequence:test.sequence});if(current!==generation.current)return;if(!r.ok||!r.file)throw Error(r.error||"Could not open this photo.");const bytes=Uint8Array.from(atob(r.file.data),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:r.file.type}));allocated.current.push(url);setUrls(prev=>({...prev,[index]:url}));}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:"Could not open this photo.");}finally{if(current===generation.current)setLoading(null);}}
  return <div className="cal-test-photos">{test.files.map(f=><div key={f.index}>{urls[f.index]?<a href={urls[f.index]} target="_blank" rel="noopener noreferrer"><img src={urls[f.index]} alt={`Test scope: ${f.name}`}/><span>Open {f.name}</span></a>:<button className="cal-button" disabled={loading!==null} onClick={()=>void open(f.index)}>{loading===f.index?"Opening photo…":`View scope photo ${f.index+1}`}</button>}</div>)}{error&&<p role="alert" className="cal-alert">{error}</p>}</div>;
}
